export const RATIO_FIELDS = [
  "early_be_trigger_ratio",
  "stage1_trigger_ratio",
  "stage2_trigger_ratio",
  "stage3_trigger_ratio",
  "break_even_trigger_ratio",
  "partial_close_trigger_ratio",
  "stage1_lock_ratio",
  "stage2_lock_ratio",
  "early_be_buffer_points",
  "stage3_atr_multiplier",
  "stage3_min_distance_ratio",
  "min_trail_distance_ratio",
  "min_early_be_trigger",
  "min_stage1_trigger",
  "min_stage1_lock",
  "min_stage2_trigger",
  "min_stage2_lock",
  "min_stage3_trigger",
  "min_break_even_trigger",
  "min_trail_distance",
] as const;
