"""
Adaptive Trend Pullback Strategy (LuxAlgo blend)
================================================

A long-only "buy the pullback in a confirmed adaptive uptrend" strategy that
fuses three LuxAlgo ideas into ONE self-contained go/no-go signal:

  * SuperTrend-AI adaptive factor — 9 SuperTrends (factors 1.0..5.0) each carry a
    running *performance memory*; a K-means (K=3) over those 9 performance values
    picks the best-performing cluster and its mean factor (`f_star`). We rebuild
    the SuperTrend on the grid factor nearest `f_star` -> the *adaptive* trend.
  * Nadaraya-Watson ENDPOINT kernel envelope (causal / non-repainting) — a
    Gaussian-weighted local mean `nwe` with a `mult*SMA(|close-nwe|,16)` band. The
    band's lower half is our discount / pullback zone.
  * Predictive Ranges stepped midline — an ATR-ratcheted `avg`; its slope is a
    slow trend-of-trend confirmation (must not be falling).

Entry (all REQUIRED, evaluated at the latest bar T, long-only):
  1. Adaptive uptrend       — trend_dir[T] == +1 (SuperTrend on nearest-grid f_star).
  2. Pullback into weakness — zone = (close-lower)/(upper-lower) in (0, 0.5], i.e.
                              at/below the kernel midline (close <= nwe) but NOT
                              broken below the lower band (close > lower_band).
  3. Fresh (not stale)      — price was more extended within the last 5 bars:
                              max(zone[T-5 .. T-1]) > 0.5 (it visited the upper
                              half of the band, then pulled back). Causal, uses
                              only prior bars.
  4. PR midline not falling  — pr_slope = sign(avg[T]-avg[T-3]) >= 0.
  5. Quality gate           — perf_score (0..10) >= min_perf_score, derived from
                              the best K-means cluster's performance vs recent
                              |Δclose|. NOTE (forced deviation): the spec asked for
                              >=7, but perf_score is STRUCTURALLY suppressed at a
                              pullback bar (a down bar drags the performance-memory
                              EMA; reaching perf_idx>=0.7 needs a near-flawless
                              up-only trend). Empirically it MAXES ~5 across real
                              equity pullbacks, so >=7 fires ~never. The default is
                              calibrated to 4.0 (top ~3% of trend+pullback
                              candidates) — a genuinely selective quality gate that
                              actually fires. The knob is exposed so the replay can
                              sweep/ablate it.
  6. Breadth / regime co-gate (market_context) — BLOCK if market_regime ==
                              'bear_confirmed' OR pct_above_sma50 < 40. A MISSING
                              market row is flagged (market_context_missing) but
                              does NOT silently block — mirrors smart_money_reclaim.
  7. Universe floors        — applied in the scanner wrapper (price/$-vol/ATR%).

NULL-CONTROL hook: pass `fixed_factor=3.0` to bypass the K-means selection and
force a single fixed SuperTrend factor (everything else identical). The replay
harness uses this to prove the adaptivity is not decorative.
ABLATION hook: pass `min_perf_score=0.0` to drop gate (5).

Design note (mirrors smart_money_reclaim / ema_cross_9_21_50): this class is PURE
— no DB, no async — so the live scanner wrapper
(`scanners/strategies/adaptive_trend_pullback.py`) and the walk-forward replay
(`analysis/adaptive_trend_pullback_replay.py`) import and run the exact same
`scan()`, guaranteeing live == backtest signal parity. Every indicator is strictly
CAUSAL (no lookahead): all recursions run left-to-right and the signal is read at
bar T only.

STATUS: pre-wiring validation build (Jul 1 2026). NOT registered in
scanner_manager / DEFAULT_ENABLED_SCANNERS and NO DB migration — validate via the
replay harness FIRST; wire only if it beats BOTH the random baseline and the
fixed-3.0 null control. Risk bracket mirrors the live auto-trader (SL capped 2.5%,
TP 7%).
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Dict, Any, List, Tuple

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class AdaptiveTrendPullbackSignal:
    """Signal generated by the adaptive-trend-pullback strategy."""
    ticker: str
    signal_type: str  # always 'BUY' (long-only)
    signal_timestamp: datetime
    entry_price: float
    stop_loss_price: float          # emitted (2.5%-capped) stop
    take_profit_price: float        # emitted 7% target
    risk_reward_ratio: float
    confidence: float               # score / 100
    quality_tier: str               # 'A' (STRONG) / 'B' (WEAK)
    composite_score: int            # 0-100 (display/ranking only — NOT a gate)

    # Technical context
    selected_factor: float = 0.0    # nearest grid factor actually used
    f_star: float = 0.0             # raw K-means best-cluster mean factor
    perf_score: int = 0
    trend_dir: int = 0
    zone: float = 0.0
    nwe: float = 0.0
    pr_slope: int = 0
    atr_14: Optional[float] = None
    sector: Optional[str] = None

    raw_data: Dict[str, Any] = field(default_factory=dict)


class AdaptiveTrendPullbackStrategy:
    """LuxAlgo blend: adaptive SuperTrend + NW kernel envelope + predictive ranges."""

    # Risk bracket — defaults mirror the LIVE stock auto-trader (SL 2.5%, TP 7%).
    DEFAULT_STOP_LOSS_PCT = 2.5
    DEFAULT_TAKE_PROFIT_PCT = 7.0

    # SuperTrend-AI
    ST_ATR_PERIOD = 10
    GRID_MIN = 1.0
    GRID_MAX = 5.0
    GRID_STEP = 0.5
    PERF_MEMORY = 10               # alpha = 2/(PERF_MEMORY+1) = 2/11
    KMEANS_K = 3
    KMEANS_ITERS = 20

    # Nadaraya-Watson endpoint envelope
    NW_H = 8
    NW_MULT = 3.0
    NW_WINDOW = 150
    NW_MAE_WINDOW = 16

    # Predictive ranges
    PR_ATR_LEN = 200
    PR_FACTOR = 6.0
    PR_SLOPE_LOOKBACK = 3

    # Other
    ATR_PERIOD = 14                # ATR-14 for structural stop
    FRESH_LOOKBACK = 5             # bars back for the "fresh pullback" test
    MIN_BARS = 60

    def __init__(
        self,
        stop_loss_pct: float = DEFAULT_STOP_LOSS_PCT,
        take_profit_pct: float = DEFAULT_TAKE_PROFIT_PCT,
        min_perf_score: float = 4.0,        # quality gate (spec asked 7; unreachable
                                            # for equities at pullback bars — see
                                            # class docstring. Ablation: set 0)
        max_zone: float = 0.5,              # pullback ceiling (lower half of band)
        min_pct_above_sma50: float = 40.0,  # breadth co-gate floor
        atr_stop_mult: float = 0.25,        # structural stop buffer (xATR)
        fixed_factor: Optional[float] = None,       # SIMPLE variant: NO k-means at
                                                    # all; trend + perf both from
                                                    # this one fixed factor's own
                                                    # perf-memory (the ship-candidate
                                                    # simplified scanner).
        force_final_factor: Optional[float] = None,  # NULL-A: run the FULL k-means
                                                     # pipeline (perf_score/gate from
                                                     # the top cluster, IDENTICAL to
                                                     # ADAPTIVE) but override ONLY the
                                                     # final trade factor to this
                                                     # fixed value. Isolates the
                                                     # factor-pick, holding the gate
                                                     # constant. Takes precedence over
                                                     # fixed_factor if both set.
    ):
        self.stop_loss_pct = stop_loss_pct
        self.take_profit_pct = take_profit_pct
        self.min_perf_score = min_perf_score
        self.max_zone = max_zone
        self.min_pct_above_sma50 = min_pct_above_sma50
        self.atr_stop_mult = atr_stop_mult
        self.fixed_factor = fixed_factor
        self.force_final_factor = force_final_factor
        self.grid = np.round(
            np.arange(self.GRID_MIN, self.GRID_MAX + 1e-9, self.GRID_STEP), 4)
        self.logger = logging.getLogger(__name__)

    # ------------------------------------------------------------------
    # Indicator helpers (pure — from raw OHLCV).
    # ------------------------------------------------------------------
    def prepare(self, df: pd.DataFrame) -> pd.DataFrame:
        """Return a copy of df with the ATR columns this strategy needs.

        Kept lightweight (ATR-10 for SuperTrend, ATR-14 for the structural stop,
        ATR for predictive ranges). The heavy per-factor recursion happens in
        scan() over the numpy arrays so the walk-forward harness stays fast-ish.
        """
        df = df.copy()
        for col in ("high", "low", "close"):
            if col not in df.columns:
                return df
        high = pd.to_numeric(df["high"], errors="coerce")
        low = pd.to_numeric(df["low"], errors="coerce")
        close = pd.to_numeric(df["close"], errors="coerce")

        prev_close = close.shift(1)
        tr = pd.concat([
            high - low,
            (high - prev_close).abs(),
            (low - prev_close).abs(),
        ], axis=1).max(axis=1)
        df["_tr"] = tr
        # ATR via SMA of true range (matches BacktestDataProvider / repo convention)
        df["atr_10"] = tr.rolling(self.ST_ATR_PERIOD).mean()
        df["atr_14"] = tr.rolling(self.ATR_PERIOD).mean()
        return df

    # ---- SuperTrend (causal) ----
    @staticmethod
    def _supertrend(high: np.ndarray, low: np.ndarray, close: np.ndarray,
                    atr: np.ndarray, factor: float) -> Tuple[np.ndarray, np.ndarray]:
        """Standard causal SuperTrend. Returns (st_line, direction ∈ {+1,-1}).

        direction = +1 (up) when the SuperTrend line sits below price, -1 (down)
        otherwise. Recursion uses only bars <= t.
        """
        n = len(close)
        hl2 = (high + low) / 2.0
        upper = hl2 + factor * atr
        lower = hl2 - factor * atr
        f_upper = np.full(n, np.nan)
        f_lower = np.full(n, np.nan)
        direction = np.ones(n, dtype=float)   # +1 up, -1 down
        st_line = np.full(n, np.nan)

        for t in range(n):
            if t == 0 or not np.isfinite(atr[t]):
                f_upper[t] = upper[t]
                f_lower[t] = lower[t]
                direction[t] = 1.0
                st_line[t] = lower[t]
                continue
            pu = f_upper[t - 1] if np.isfinite(f_upper[t - 1]) else upper[t]
            pl = f_lower[t - 1] if np.isfinite(f_lower[t - 1]) else lower[t]
            # final bands
            f_upper[t] = upper[t] if (upper[t] < pu or close[t - 1] > pu) else pu
            f_lower[t] = lower[t] if (lower[t] > pl or close[t - 1] < pl) else pl
            # direction
            if close[t] > pu:
                direction[t] = 1.0
            elif close[t] < pl:
                direction[t] = -1.0
            else:
                direction[t] = direction[t - 1]
            st_line[t] = f_lower[t] if direction[t] > 0 else f_upper[t]
        return st_line, direction

    # ---- Performance memory (causal EMA-like pass) ----
    def _perf_memory(self, close: np.ndarray, direction: np.ndarray) -> np.ndarray:
        """P[t] = P[t-1] + alpha*((close[t]-close[t-1])*dir[t-1] - P[t-1]).

        Uses dir[t-1] (previous bar's direction) -> strictly causal. P[0]=0.
        Equivalent to an EMA(alpha) of x[t]=(close[t]-close[t-1])*dir[t-1].
        """
        alpha = 2.0 / (self.PERF_MEMORY + 1.0)
        n = len(close)
        p = np.zeros(n)
        for t in range(1, n):
            x = (close[t] - close[t - 1]) * direction[t - 1]
            p[t] = p[t - 1] + alpha * (x - p[t - 1])
        return p

    # ---- K-means over the 9 performance values at bar T ----
    def _kmeans_1d(self, vals: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        """Deterministic 1-D K-means (K=3), quartile init [p25,p50,p75].

        Returns (labels, centroids). Iterates <= KMEANS_ITERS until stable.
        """
        vals = np.asarray(vals, dtype=float)
        centroids = np.array([
            np.percentile(vals, 25),
            np.percentile(vals, 50),
            np.percentile(vals, 75),
        ], dtype=float)
        labels = np.zeros(len(vals), dtype=int)
        for _ in range(self.KMEANS_ITERS):
            dist = np.abs(vals[:, None] - centroids[None, :])
            labels = dist.argmin(axis=1)
            new = centroids.copy()
            for c in range(self.KMEANS_K):
                mask = labels == c
                if mask.any():
                    new[c] = vals[mask].mean()
            if np.allclose(new, centroids):
                centroids = new
                break
            centroids = new
        return labels, centroids

    # ---- Nadaraya-Watson ENDPOINT (causal, non-repainting) ----
    def _nwe_endpoint(self, close: np.ndarray, end_idx: int) -> float:
        """Gaussian-weighted endpoint mean using only bars <= end_idx."""
        w_len = min(self.NW_WINDOW, end_idx + 1)
        i = np.arange(w_len)
        w = np.exp(-(i ** 2) / (2.0 * self.NW_H ** 2))
        seg = close[end_idx - w_len + 1:end_idx + 1][::-1]   # seg[i] = close[end-i]
        return float((seg * w).sum() / w.sum())

    # ---- Predictive ranges stepped midline (causal ratchet) ----
    def _predictive_avg(self, close: np.ndarray, atr_pr: np.ndarray) -> np.ndarray:
        """ATR-ratcheted midline: avg += atr if breakout up, -= atr if down, else hold."""
        n = len(close)
        avg = np.empty(n)
        avg[0] = close[0]
        for t in range(1, n):
            a = atr_pr[t]
            if not np.isfinite(a):
                avg[t] = avg[t - 1]
            elif close[t] - avg[t - 1] > a:
                avg[t] = avg[t - 1] + a
            elif avg[t - 1] - close[t] > a:
                avg[t] = avg[t - 1] - a
            else:
                avg[t] = avg[t - 1]
        return avg

    # ------------------------------------------------------------------
    # Live last-bar path (used by the scanner wrapper AND the replay sim).
    # ------------------------------------------------------------------
    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        metrics: Optional[Dict[str, Any]] = None,
        market: Optional[Dict[str, Any]] = None,
        sector: Optional[str] = None,
    ) -> Optional[AdaptiveTrendPullbackSignal]:
        """Evaluate the most recent bar; return a signal or None.

        Args:
            df:      daily OHLCV, newest-last (~365 bars).
            ticker:  symbol.
            metrics: optional latest stock_screening_metrics row-dict (AS-OF the
                     signal date — the caller must not pass future data).
            market:  optional latest market_context row-dict (market_regime,
                     pct_above_sma50). None -> breadth co-gate flagged missing.
        """
        if df is None or df.empty or len(df) < self.MIN_BARS:
            return None

        df = self.prepare(df)
        if "atr_10" not in df.columns:
            return None

        n = len(df)
        T = n - 1
        high = pd.to_numeric(df["high"], errors="coerce").to_numpy()
        low = pd.to_numeric(df["low"], errors="coerce").to_numpy()
        close = pd.to_numeric(df["close"], errors="coerce").to_numpy()
        atr10 = df["atr_10"].to_numpy()
        atr14_arr = df["atr_14"].to_numpy()

        close_t = float(close[T])
        if not np.isfinite(close_t) or close_t <= 0:
            return None
        if not np.isfinite(atr10[T]):
            return None

        # ------------------------------------------------------------------
        # (A) SuperTrend per grid factor + (B) per-factor performance memory.
        # ------------------------------------------------------------------
        st_lines: Dict[float, np.ndarray] = {}
        dirs: Dict[float, np.ndarray] = {}
        perf_t = np.zeros(len(self.grid))
        for k, f in enumerate(self.grid):
            st_line, direction = self._supertrend(high, low, close, atr10, float(f))
            st_lines[float(f)] = st_line
            dirs[float(f)] = direction
            p = self._perf_memory(close, direction)
            perf_t[k] = p[T]

        # ------------------------------------------------------------------
        # (C) Factor selection — THREE cleanly-separated modes:
        #
        #   ADAPTIVE (default): K-means over the 9 perf values -> best cluster ->
        #       f_star -> nearest grid factor drives the trade; perf gate uses the
        #       top cluster centroid.
        #
        #   NULL-A (force_final_factor set): run the FULL identical K-means pipeline
        #       so perf_score / the quality gate are computed EXACTLY as ADAPTIVE
        #       (top cluster centroid), but override ONLY the final trade factor to a
        #       fixed value. Changes only the factor that determines the trade,
        #       holding the gate constant -> isolates whether the adaptive factor
        #       pick adds anything.
        #
        #   SIMPLE (fixed_factor set, no k-means): trend AND perf both come from one
        #       fixed factor's OWN perf-memory. The standalone simplified scanner.
        # ------------------------------------------------------------------
        if self.force_final_factor is not None:
            # NULL-A: gate from k-means (identical to ADAPTIVE), trade factor forced.
            labels, centroids = self._kmeans_1d(perf_t)
            best_cluster = int(np.argmax(centroids))
            best_centroid = float(centroids[best_cluster])
            in_best = self.grid[labels == best_cluster]
            kmeans_f_star = float(in_best.mean()) if len(in_best) else float(np.median(self.grid))
            grid_idx = int(np.argmin(np.abs(self.grid - self.force_final_factor)))
            nearest_grid = float(self.grid[grid_idx])
            f_star = float(self.force_final_factor)
        elif self.fixed_factor is not None:
            # SIMPLE: no k-means; trend + perf gate both from this one factor.
            grid_idx = int(np.argmin(np.abs(self.grid - self.fixed_factor)))
            nearest_grid = float(self.grid[grid_idx])
            f_star = float(self.fixed_factor)
            best_centroid = float(perf_t[grid_idx])   # own performance
            kmeans_f_star = f_star
        else:
            # ADAPTIVE
            labels, centroids = self._kmeans_1d(perf_t)
            best_cluster = int(np.argmax(centroids))
            best_centroid = float(centroids[best_cluster])
            in_best = self.grid[labels == best_cluster]
            f_star = float(in_best.mean()) if len(in_best) else float(np.median(self.grid))
            grid_idx = int(np.argmin(np.abs(self.grid - f_star)))
            nearest_grid = float(self.grid[grid_idx])
            kmeans_f_star = f_star

        # ------------------------------------------------------------------
        # (D) perf_score (0..10) at T.
        # ------------------------------------------------------------------
        abs_dc = np.abs(np.diff(close, prepend=close[0]))
        den_series = pd.Series(abs_dc).ewm(
            alpha=2.0 / (self.PERF_MEMORY + 1.0), adjust=False).mean().to_numpy()
        den = float(den_series[T])
        perf_idx = (max(best_centroid, 0.0) / den) if den > 0 else 0.0
        perf_score = int(round(float(np.clip(perf_idx, 0.0, 1.0)) * 10))

        # ------------------------------------------------------------------
        # (E) Final adaptive trend from the nearest-grid factor.
        # ------------------------------------------------------------------
        trend_dir = int(dirs[nearest_grid][T])
        st_line_t = float(st_lines[nearest_grid][T])

        # ------------------------------------------------------------------
        # (F) Nadaraya-Watson endpoint envelope + MAE band (causal).
        # ------------------------------------------------------------------
        nwe_t = self._nwe_endpoint(close, T)
        # MAE = mult * SMA(|close - nwe_endpoint|, 16) over trailing endpoints.
        mae_start = max(0, T - self.NW_MAE_WINDOW + 1)
        resid = []
        for j in range(mae_start, T + 1):
            nwe_j = self._nwe_endpoint(close, j)
            resid.append(abs(close[j] - nwe_j))
        mae = self.NW_MULT * float(np.mean(resid)) if resid else 0.0
        lower_band = nwe_t - mae
        upper_band = nwe_t + mae
        band_w = upper_band - lower_band
        zone = float((close_t - lower_band) / band_w) if band_w > 0 else 1.0

        # zone series (for the "fresh pullback" test) over the recent window.
        def _zone_at(idx: int) -> float:
            nwe_i = self._nwe_endpoint(close, idx)
            s = max(0, idx - self.NW_MAE_WINDOW + 1)
            r = [abs(close[j] - self._nwe_endpoint(close, j)) for j in range(s, idx + 1)]
            m = self.NW_MULT * float(np.mean(r)) if r else 0.0
            lo = nwe_i - m
            bw = 2.0 * m
            return float((close[idx] - lo) / bw) if bw > 0 else 1.0

        # ------------------------------------------------------------------
        # (G) Predictive ranges stepped midline + slope.
        # ------------------------------------------------------------------
        pr_len = min(self.PR_ATR_LEN, n)
        atr_pr = df["_tr"].rolling(pr_len).mean().to_numpy() * self.PR_FACTOR
        pr_avg = self._predictive_avg(close, atr_pr)
        k = self.PR_SLOPE_LOOKBACK
        pr_slope = int(np.sign(pr_avg[T] - pr_avg[T - k])) if T - k >= 0 else 0

        # ==================================================================
        # ENTRY GATES (long-only, all REQUIRED).
        # ==================================================================
        # (1) adaptive uptrend confirmed
        if trend_dir != 1:
            return None
        # (2) pullback into weakness: lower half of band, not broken down
        if not (0.0 < zone <= self.max_zone):
            return None
        # (3) fresh pullback: price was extended (upper half) within last 5 bars
        recent = [
            _zone_at(idx) for idx in range(max(0, T - self.FRESH_LOOKBACK), T)
        ]
        fresh = any(z > 0.5 for z in recent) if recent else False
        if not fresh:
            return None
        # (4) predictive-range midline not falling
        if pr_slope < 0:
            return None
        # (5) quality gate
        if perf_score < self.min_perf_score:
            return None
        # (6) breadth / regime co-gate (hard gate — missing flagged, not blocked)
        market_regime = None
        pct_above_sma50 = None
        market_context_missing = market is None
        breadth_blocked = False
        if market is not None:
            market_regime = market.get("market_regime")
            psa = market.get("pct_above_sma50")
            try:
                pct_above_sma50 = float(psa) if psa is not None else None
            except (TypeError, ValueError):
                pct_above_sma50 = None
            if market_regime == "bear_confirmed":
                breadth_blocked = True
            if pct_above_sma50 is not None and pct_above_sma50 < self.min_pct_above_sma50:
                breadth_blocked = True
        if breadth_blocked:
            return None

        # ------------------------------------------------------------------
        # Entry / stop / target.
        # ------------------------------------------------------------------
        atr_14 = float(atr14_arr[T]) if np.isfinite(atr14_arr[T]) else 0.0
        entry = close_t
        structural_stop = st_line_t - self.atr_stop_mult * atr_14
        emitted_stop = max(structural_stop, entry * (1 - self.stop_loss_pct / 100.0))
        emitted_tp1 = entry * (1 + self.take_profit_pct / 100.0)
        risk = entry - emitted_stop
        reward = emitted_tp1 - entry
        rr = round(reward / risk, 2) if risk > 0 else 0.0
        structural_tp_3r = entry + 3.0 * (entry - structural_stop)

        # ------------------------------------------------------------------
        # Display/ranking score (NOT a gate — go/no-go is fully above).
        # ------------------------------------------------------------------
        # reward deeper pullbacks (lower zone) + stronger perf.
        zone_bonus = (0.5 - zone) / 0.5 * 20.0     # 0..20
        score = int(round(float(np.clip(perf_score * 8.0 + zone_bonus, 0.0, 100.0))))
        tier = "A" if perf_score >= 8 else "B"
        confidence = round(score / 100.0, 4)

        ts = df["timestamp"].iloc[T] if "timestamp" in df.columns and pd.notna(
            df["timestamp"].iloc[T]) else datetime.now()

        raw_data = {
            "selected_factor": nearest_grid,
            "f_star": round(f_star, 4),
            "kmeans_f_star": round(kmeans_f_star, 4),
            "perf_values": [round(float(v), 6) for v in perf_t.tolist()],
            "perf_grid": [float(g) for g in self.grid.tolist()],
            "best_cluster_centroid": round(best_centroid, 6),
            "perf_score": perf_score,
            "perf_idx": round(perf_idx, 6),
            "trend_dir": trend_dir,
            "st_line": round(st_line_t, 4),
            "nwe": round(nwe_t, 4),
            "lower_band": round(lower_band, 4),
            "upper_band": round(upper_band, 4),
            "zone": round(zone, 4),
            "fresh_pullback": fresh,
            "pr_avg": round(float(pr_avg[T]), 4),
            "pr_slope": pr_slope,
            "atr_14": round(atr_14, 4),
            "structural_stop": round(structural_stop, 4),
            "structural_tp_3R": round(structural_tp_3r, 4),
            "market_regime": market_regime,
            "pct_above_sma50": pct_above_sma50,
            "breadth_blocked": breadth_blocked,
            "market_context_missing": market_context_missing,
            "mode": ("null_a" if self.force_final_factor is not None
                     else "simple" if self.fixed_factor is not None
                     else "adaptive"),
        }

        return AdaptiveTrendPullbackSignal(
            ticker=ticker,
            signal_type="BUY",
            signal_timestamp=ts,
            entry_price=round(entry, 4),
            stop_loss_price=round(emitted_stop, 4),
            take_profit_price=round(emitted_tp1, 4),
            risk_reward_ratio=rr,
            confidence=confidence,
            quality_tier=tier,
            composite_score=score,
            selected_factor=nearest_grid,
            f_star=round(f_star, 4),
            perf_score=perf_score,
            trend_dir=trend_dir,
            zone=round(zone, 4),
            nwe=round(nwe_t, 4),
            pr_slope=pr_slope,
            atr_14=round(atr_14, 4),
            sector=sector,
            raw_data=raw_data,
        )

    def get_config(self) -> Dict[str, Any]:
        return {
            "strategy_name": "ADAPTIVE_TREND_PULLBACK",
            "stop_loss_pct": self.stop_loss_pct,
            "take_profit_pct": self.take_profit_pct,
            "st_atr_period": self.ST_ATR_PERIOD,
            "grid": [float(g) for g in self.grid.tolist()],
            "perf_memory": self.PERF_MEMORY,
            "kmeans_k": self.KMEANS_K,
            "nw_h": self.NW_H,
            "nw_mult": self.NW_MULT,
            "pr_atr_len": self.PR_ATR_LEN,
            "pr_factor": self.PR_FACTOR,
            "min_perf_score": self.min_perf_score,
            "max_zone": self.max_zone,
            "min_pct_above_sma50": self.min_pct_above_sma50,
            "fixed_factor": self.fixed_factor,
        }
