"""
EMA 9/21/50 Cross Strategy
==========================

A momentum-pullback long entry. In an established uptrend the strategy waits
for a shallow dip to the fast EMA and buys the reclaim:

Entry conditions (all required, long-only):
  1. close > EMA 50   (intermediate uptrend intact)
  2. close > EMA 21   (short-term uptrend intact)
  3. close crosses UP through EMA 9  (was at/below the 9 on the prior bar,
     closes above it now)  --> the entry trigger

Rationale: requiring price to already sit above the 21 and 50 EMAs keeps us in
a trend; the 9-EMA reclaim is the timing trigger off a minor pullback, so we
buy strength resuming rather than chasing extension.

Design note: the entry test is implemented ONCE, vectorised, in
`detect_signals(df)`. `scan()` (the live last-bar path) and the walk-forward
backtest (`analysis/ema_cross_replay.py`) both consume that same boolean
Series, so live signals and backtested signals are guaranteed identical.

EMA 9 and EMA 21 are NOT produced by BacktestDataProvider (it only emits
20/50/100/200), so this class computes the 9/21 itself from `close`. EMA 50 is
reused from the provider when present, otherwise computed here, so the class is
self-contained for the backtest harness too.
"""

import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Dict, Any
import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class EmaCrossSignal:
    """Signal generated by the EMA 9/21/50 cross strategy."""
    ticker: str
    signal_type: str  # always 'BUY' (long-only)
    signal_timestamp: datetime
    entry_price: float
    stop_loss_price: float
    take_profit_price: float
    risk_reward_ratio: float
    confidence: float
    quality_tier: str

    # Technical context
    ema_9: float
    ema_21: float
    ema_50: float
    rsi: Optional[float] = None
    atr: Optional[float] = None
    sector: Optional[str] = None
    volume: Optional[int] = None
    relative_volume: Optional[float] = None


class EmaCross92150Strategy:
    """EMA 9/21/50 cross momentum-pullback strategy (long-only)."""

    # Risk bracket — defaults mirror the LIVE stock auto-trader
    # (stock_auto_trade_settings: SL 2.5%, TP 7%, ATR stop disabled).
    DEFAULT_STOP_LOSS_PCT = 2.5
    DEFAULT_TAKE_PROFIT_PCT = 7.0

    def __init__(
        self,
        stop_loss_pct: float = DEFAULT_STOP_LOSS_PCT,
        take_profit_pct: float = DEFAULT_TAKE_PROFIT_PCT,
        ema_fast: int = 9,
        ema_mid: int = 21,
        ema_slow: int = 50,
        min_price: float = 3.0,
        min_relative_volume: float = 0.0,  # 0 = volume filter off
        require_stack: bool = True,        # require 9>21>50 stack (validated Jun-30)
    ):
        self.stop_loss_pct = stop_loss_pct
        self.take_profit_pct = take_profit_pct
        self.ema_fast = ema_fast
        self.ema_mid = ema_mid
        self.ema_slow = ema_slow
        self.min_price = min_price
        self.min_relative_volume = min_relative_volume
        self.require_stack = require_stack
        self.logger = logging.getLogger(__name__)

    # ------------------------------------------------------------------
    # Core (vectorised) entry detection — single source of truth.
    # ------------------------------------------------------------------
    def prepare(self, df: pd.DataFrame) -> pd.DataFrame:
        """Return a copy of df with the EMA columns this strategy needs.

        ema_9 / ema_21 are always (re)computed here. ema_50 is reused from the
        provider when present and otherwise computed, so this works both for the
        live scanner (provider supplies ema_50) and the backtest (raw candles).
        """
        df = df.copy()
        if "close" not in df.columns:
            return df
        close = pd.to_numeric(df["close"], errors="coerce")
        df["ema_9"] = close.ewm(span=self.ema_fast, adjust=False).mean()
        df["ema_21"] = close.ewm(span=self.ema_mid, adjust=False).mean()
        if "ema_50" not in df.columns:
            df["ema_50"] = close.ewm(span=self.ema_slow, adjust=False).mean()
        df["_above_ema9"] = close > df["ema_9"]
        df["_prev_above_ema9"] = df["_above_ema9"].shift(1)
        # conviction inputs (validated Jun-30 ranker): trend persistence leads
        df["_ema50_slope"] = df["ema_50"].pct_change(5) * 100
        df["_ret_60d"] = close.pct_change(60) * 100
        rng = (pd.to_numeric(df["high"], errors="coerce")
               - pd.to_numeric(df["low"], errors="coerce")).replace(0, np.nan)
        df["_range_pos"] = (close - pd.to_numeric(df["low"], errors="coerce")) / rng
        return df

    def detect_signals(self, df: pd.DataFrame) -> pd.Series:
        """Boolean Series, True on bars where the entry triggers.

        This is the ONE place the entry rule lives. Both the live `scan()` and
        the walk-forward backtest evaluate this exact expression.
        """
        if df.empty or "ema_9" not in df.columns:
            return pd.Series(False, index=df.index)

        close = pd.to_numeric(df["close"], errors="coerce")

        cond_above_50 = close > df["ema_50"]
        cond_above_21 = close > df["ema_21"]
        # cross UP through the 9: below/at on prior bar, above now
        cond_cross_9 = df["_above_ema9"] & (~df["_prev_above_ema9"].fillna(False))

        signal = cond_above_50 & cond_above_21 & cond_cross_9

        # validated entry gate: full EMA stack 9>=21>=50 (regime/trend quality)
        if self.require_stack:
            signal &= (df["ema_9"] >= df["ema_21"]) & (df["ema_21"] >= df["ema_50"])

        # Optional liquidity / quality floors
        if self.min_price > 0:
            signal &= close >= self.min_price
        if self.min_relative_volume > 0 and "relative_volume" in df.columns:
            rv = pd.to_numeric(df["relative_volume"], errors="coerce")
            signal &= rv.fillna(0) >= self.min_relative_volume

        # never fire where EMAs are undefined
        signal &= df[["ema_9", "ema_21", "ema_50"]].notna().all(axis=1)
        return signal.fillna(False)

    # ------------------------------------------------------------------
    # Live last-bar path (used by the scanner wrapper).
    # ------------------------------------------------------------------
    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        sector: Optional[str] = None,
    ) -> Optional[EmaCrossSignal]:
        """Evaluate the most recent bar; return a signal or None."""
        min_bars = self.ema_slow + 5
        if df.empty or len(df) < min_bars:
            return None

        df = self.prepare(df)
        sig = self.detect_signals(df)
        if not bool(sig.iloc[-1]):
            return None

        current = df.iloc[-1]
        entry_price = float(current["close"])
        stop_loss_price = entry_price * (1 - self.stop_loss_pct / 100)
        take_profit_price = entry_price * (1 + self.take_profit_pct / 100)
        risk = entry_price - stop_loss_price
        reward = take_profit_price - entry_price
        rr = reward / risk if risk > 0 else 0.0

        confidence = self._confidence(current)
        tier = self._tier(confidence)

        ts = current["timestamp"] if pd.notna(current.get("timestamp")) else datetime.now()

        return EmaCrossSignal(
            ticker=ticker,
            signal_type="BUY",
            signal_timestamp=ts,
            entry_price=round(entry_price, 4),
            stop_loss_price=round(stop_loss_price, 4),
            take_profit_price=round(take_profit_price, 4),
            risk_reward_ratio=round(rr, 2),
            confidence=round(confidence, 4),
            quality_tier=tier,
            ema_9=round(float(current["ema_9"]), 4),
            ema_21=round(float(current["ema_21"]), 4),
            ema_50=round(float(current["ema_50"]), 4),
            rsi=round(float(current["rsi"]), 2) if pd.notna(current.get("rsi")) else None,
            atr=round(float(current["atr"]), 4) if pd.notna(current.get("atr")) else None,
            sector=sector,
            volume=int(current["volume"]) if pd.notna(current.get("volume")) else None,
            relative_volume=round(float(current["relative_volume"]), 2)
            if pd.notna(current.get("relative_volume")) else None,
        )

    # ------------------------------------------------------------------
    # Confidence / tier (a soft quality score; does NOT gate entry).
    # ------------------------------------------------------------------
    def _confidence(self, current: pd.Series) -> float:
        """Conviction score driving the auto-trader's top-pool RANK.

        Validated Jun-30: ranking each day's candidates by TREND PERSISTENCE
        (EMA50 slope) and taking the best few lifts PF ~1.07 -> ~1.7. This score
        is dominated by trend persistence + medium-term momentum so the live
        top-50 / score>=65 selection reproduces that top-K effect. It does NOT
        gate entry (detect_signals already did).
        """
        score = 0.40  # base for any valid stacked cross

        # trend persistence (lead signal): EMA50 5-bar slope %, ~[-2,+2] typical
        slope = current.get("_ema50_slope")
        if pd.notna(slope):
            score += 0.25 * max(0.0, min(1.0, float(slope) / 2.0))

        # medium-term momentum: 60d return %, saturate at +30%
        ret60 = current.get("_ret_60d")
        if pd.notna(ret60):
            score += 0.20 * max(0.0, min(1.0, float(ret60) / 30.0))

        # cross-bar conviction: close position in the day's range
        rpos = current.get("_range_pos")
        if pd.notna(rpos):
            score += 0.10 * max(0.0, min(1.0, float(rpos)))

        # healthy (not overbought) momentum + participation (minor)
        rsi = current.get("rsi")
        if pd.notna(rsi) and 45 <= rsi <= 70:
            score += 0.05
        return float(min(1.0, score))

    @staticmethod
    def _tier(confidence: float) -> str:
        if confidence >= 0.85:
            return "A+"
        if confidence >= 0.70:
            return "A"
        if confidence >= 0.60:
            return "B"
        if confidence >= 0.50:
            return "C"
        return "D"

    def get_config(self) -> Dict[str, Any]:
        return {
            "strategy_name": "EMA_CROSS_9_21_50",
            "stop_loss_pct": self.stop_loss_pct,
            "take_profit_pct": self.take_profit_pct,
            "ema_fast": self.ema_fast,
            "ema_mid": self.ema_mid,
            "ema_slow": self.ema_slow,
            "min_price": self.min_price,
            "min_relative_volume": self.min_relative_volume,
        }
