"""
Smart Money Reclaim Strategy (LuxAlgo-inspired)
===============================================

A long-only sweep-and-reclaim reversal built around a Chaikin money-flow
*bullish divergence*. The idea (LuxAlgo "smart money" framing): a prior swing
low gets liquidity-swept (a lower low), but money flow (accumulation) is
*rising* into that sweep — smart money is absorbing the flush — and price then
reclaims the swept level. We buy that reclaim from a discount zone.

Entry conditions (all REQUIRED, evaluated at the latest bar T, long-only):
  1. Swing low     — 5-bar fractal low over the trailing 40 bars before the
                     sweep window (SWING_LOW value + bar index i_sl).
  2. Sweep         — within the last 3 bars a bar printed low < SWING_LOW.
  3. Reclaim       — close_T >= SWING_LOW * 0.998 (price back above the level).
  4. MF divergence — CMF_5 at the sweep bar > CMF_5 at the swing-low bar i_sl
                     (accumulation while price made a lower low). THE CORE EDGE.
  5. Volume conf   — relative_volume at reclaim >= 1.5.
  6. Overflow rej  — reject if relative_volume >= 3.0 AND MFM_T <= -0.5 (blow-off).
  7. Discount zone — ZONE_POS = (close - min(low,60)) / (max(high,60)-min(low,60))
                     must be <= 0.35.
  8. Breadth co-gate (market_context) — BLOCK if market_regime == 'bear_confirmed'
                     OR pct_above_sma50 < 35. Missing market row does NOT silently
                     pass: it is flagged (market_context_missing) but not blocked.

Design note (mirrors ema_cross_9_21_50): this class is PURE — no DB, no async —
so the live scanner wrapper (`scanners/strategies/smart_money_reclaim.py`) and the
walk-forward replay (`analysis/smart_money_reclaim_replay.py`) both import and
run the exact same `scan()`, guaranteeing live == backtest signal parity.

Chaikin money flow (per bar):
    MFM   = ((close-low) - (high-close)) / (high-low)      # 0 if high==low
    MFV   = MFM * volume
    CMF_N = rolling_sum(MFV, N) / rolling_sum(volume, N)   # N = 5 and 20

STATUS: monitor-only forward-test (Jul 1 2026). Emits signals for the pipeline
but is excluded from the live tradable pool via MONITOR_ONLY_SCANNERS in
trading-ui/app/api/signals/top/route.ts. Risk bracket mirrors the live
auto-trader (SL capped 2.5%, TP 7%) so its forward outcomes are directly
comparable with ema_cross_9_21_50.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Dict, Any

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


@dataclass
class SmartMoneyReclaimSignal:
    """Signal generated by the smart-money sweep-reclaim strategy."""
    ticker: str
    signal_type: str  # always 'BUY' (long-only reversal)
    signal_timestamp: datetime
    entry_price: float
    stop_loss_price: float          # emitted (2.5%-capped) stop
    take_profit_price: float        # emitted 7% target
    risk_reward_ratio: float
    confidence: float               # score / 100
    quality_tier: str               # 'A' (STRONG) / 'B' (WEAK)
    composite_score: int            # 0-100 confluence score

    # Technical context
    swing_low: float = 0.0
    sweep_low: float = 0.0
    zone_pos: float = 0.0
    cmf_5: Optional[float] = None
    cmf_20: Optional[float] = None
    mfm_t: Optional[float] = None
    divergence_delta: float = 0.0
    relative_volume: Optional[float] = None
    atr_14: Optional[float] = None
    sector: Optional[str] = None

    raw_data: Dict[str, Any] = field(default_factory=dict)


class SmartMoneyReclaimStrategy:
    """LuxAlgo-inspired money-flow-divergence sweep-reclaim strategy (long-only)."""

    # Risk bracket — defaults mirror the LIVE stock auto-trader (SL 2.5%, TP 7%).
    DEFAULT_STOP_LOSS_PCT = 2.5     # emitted risk cap
    DEFAULT_TAKE_PROFIT_PCT = 7.0

    # Detection parameters
    CMF_FAST = 5
    CMF_SLOW = 20
    SWING_LOOKBACK = 40             # bars scanned for the fractal swing low
    SWEEP_WINDOW = 3               # bars in which the sweep+reclaim must occur
    ZONE_LOOKBACK = 60             # discount-zone range window
    ATR_PERIOD = 14

    def __init__(
        self,
        stop_loss_pct: float = DEFAULT_STOP_LOSS_PCT,
        take_profit_pct: float = DEFAULT_TAKE_PROFIT_PCT,
        min_volume_conf: float = 1.5,       # required rvol at reclaim
        overflow_rvol: float = 3.0,         # blow-off reject rvol
        overflow_mfm: float = -0.5,         # blow-off reject MFM
        max_zone_pos: float = 0.35,         # discount-zone ceiling
        reclaim_tol: float = 0.998,         # close >= SWING_LOW * tol
        min_pct_above_sma50: float = 35.0,  # breadth co-gate floor
        min_score: int = 55,                # self-contained go/no-go
        atr_stop_mult: float = 0.25,        # structural stop buffer (xATR)
    ):
        self.stop_loss_pct = stop_loss_pct
        self.take_profit_pct = take_profit_pct
        self.min_volume_conf = min_volume_conf
        self.overflow_rvol = overflow_rvol
        self.overflow_mfm = overflow_mfm
        self.max_zone_pos = max_zone_pos
        self.reclaim_tol = reclaim_tol
        self.min_pct_above_sma50 = min_pct_above_sma50
        self.min_score = min_score
        self.atr_stop_mult = atr_stop_mult
        self.logger = logging.getLogger(__name__)

    # ------------------------------------------------------------------
    # Indicator helpers (pure — computed from raw OHLCV so the backtest
    # harness works on bare candles, no provider indicators required).
    # ------------------------------------------------------------------
    def prepare(self, df: pd.DataFrame) -> pd.DataFrame:
        """Return a copy of df with money-flow + ATR columns this strategy needs."""
        df = df.copy()
        for col in ("high", "low", "close", "volume"):
            if col not in df.columns:
                return df
        high = pd.to_numeric(df["high"], errors="coerce")
        low = pd.to_numeric(df["low"], errors="coerce")
        close = pd.to_numeric(df["close"], errors="coerce")
        volume = pd.to_numeric(df["volume"], errors="coerce").fillna(0.0)

        rng = (high - low).replace(0, np.nan)
        mfm = ((close - low) - (high - close)) / rng
        mfm = mfm.fillna(0.0)          # 0 when high == low
        mfv = mfm * volume
        df["mfm"] = mfm
        df["cmf_5"] = (mfv.rolling(self.CMF_FAST).sum()
                       / volume.rolling(self.CMF_FAST).sum().replace(0, np.nan))
        df["cmf_20"] = (mfv.rolling(self.CMF_SLOW).sum()
                        / volume.rolling(self.CMF_SLOW).sum().replace(0, np.nan))

        # ATR-14 (SMA of true range — matches BacktestDataProvider convention)
        prev_close = close.shift(1)
        tr = pd.concat([
            high - low,
            (high - prev_close).abs(),
            (low - prev_close).abs(),
        ], axis=1).max(axis=1)
        df["atr_14"] = tr.rolling(self.ATR_PERIOD).mean()

        # fallback relative_volume (volume / trailing-20 avg) if not supplied
        df["_rvol_calc"] = volume / volume.rolling(20).mean().replace(0, np.nan)
        return df

    @staticmethod
    def _find_swing_low(low: np.ndarray, hi_idx: int, lookback: int):
        """Most-recent 5-bar fractal low in [hi_idx-lookback, hi_idx-1].

        A fractal low at i requires low[i] == min(low[i-2 .. i+2]). Returns
        (swing_low_value, i_sl) or (None, None) if none found.
        """
        start = max(2, hi_idx - lookback)
        # walk backwards from most-recent to oldest, first hit wins
        for i in range(hi_idx - 1, start - 1, -1):
            if i - 2 < 0 or i + 2 >= len(low):
                continue
            window = low[i - 2:i + 3]
            if np.isnan(window).any():
                continue
            if low[i] == window.min():
                return float(low[i]), i
        return None, None

    # ------------------------------------------------------------------
    # Live last-bar path (used by the scanner wrapper AND the replay sim).
    # ------------------------------------------------------------------
    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        metrics: Optional[Dict[str, Any]] = None,
        market: Optional[Dict[str, Any]] = None,
        sector: Optional[str] = None,
    ) -> Optional[SmartMoneyReclaimSignal]:
        """Evaluate the most recent bar; return a signal or None.

        Args:
            df:      daily OHLCV, newest-last (~200 bars).
            ticker:  symbol.
            metrics: optional latest stock_screening_metrics row-dict
                     (relative_volume, rs_trend, rs_vs_spy, ...). AS-OF the
                     signal date — the caller must not pass future data.
            market:  optional latest market_context row-dict
                     (market_regime, pct_above_sma50). None -> breadth co-gate
                     is flagged missing (not silently passed).
        """
        min_bars = self.SWING_LOOKBACK + self.ZONE_LOOKBACK + 5
        if df is None or df.empty or len(df) < min_bars:
            return None

        df = self.prepare(df)
        if "cmf_5" not in df.columns:
            return None

        n = len(df)
        T = n - 1
        low = pd.to_numeric(df["low"], errors="coerce").to_numpy()
        high = pd.to_numeric(df["high"], errors="coerce").to_numpy()
        close = pd.to_numeric(df["close"], errors="coerce").to_numpy()
        cmf5 = df["cmf_5"].to_numpy()

        close_t = float(close[T])
        if not np.isfinite(close_t) or close_t <= 0:
            return None

        # --- (1) swing low: fractal over the trailing 40 bars BEFORE the sweep window
        sweep_start = T - (self.SWEEP_WINDOW - 1)          # first bar of sweep window
        swing_low, i_sl = self._find_swing_low(low, sweep_start, self.SWING_LOOKBACK)
        if swing_low is None:
            return None

        # --- (2) sweep: some bar in the last 3 printed low < SWING_LOW
        window_lows = low[sweep_start:T + 1]
        if np.isnan(window_lows).all():
            return None
        sweep_off = int(np.nanargmin(window_lows))
        sweep_idx = sweep_start + sweep_off
        sweep_low = float(low[sweep_idx])
        if not (sweep_low < swing_low):
            return None

        # --- (3) reclaim: latest close back above the swept level
        if close_t < swing_low * self.reclaim_tol:
            return None

        # --- (4) money-flow bullish divergence (CORE): CMF_5 rising into the sweep
        cmf5_sweep = cmf5[sweep_idx]
        cmf5_swinglow = cmf5[i_sl]
        if not (np.isfinite(cmf5_sweep) and np.isfinite(cmf5_swinglow)):
            return None
        divergence_delta = float(cmf5_sweep - cmf5_swinglow)
        if not (divergence_delta > 0):
            return None

        # --- (5) volume confirmation at the reclaim bar
        rvol = None
        if metrics is not None and metrics.get("relative_volume") is not None:
            try:
                rvol = float(metrics["relative_volume"])
            except (TypeError, ValueError):
                rvol = None
        if rvol is None or not np.isfinite(rvol):
            rv_calc = df["_rvol_calc"].to_numpy()[T]
            rvol = float(rv_calc) if np.isfinite(rv_calc) else 0.0
        if rvol < self.min_volume_conf:
            return None

        # --- (6) overflow (blow-off) reject
        mfm_t = float(df["mfm"].to_numpy()[T])
        overflow_rejected = (rvol >= self.overflow_rvol and mfm_t <= self.overflow_mfm)
        if overflow_rejected:
            return None

        # --- (7) discount-zone gate
        lo60 = np.nanmin(low[max(0, T - self.ZONE_LOOKBACK + 1):T + 1])
        hi60 = np.nanmax(high[max(0, T - self.ZONE_LOOKBACK + 1):T + 1])
        zrange = hi60 - lo60
        zone_pos = float((close_t - lo60) / zrange) if zrange > 0 else 1.0
        if zone_pos > self.max_zone_pos:
            return None

        # --- (8) breadth / regime co-gate (hard gate — do not silently pass)
        market_regime = None
        pct_above_sma50 = None
        market_context_missing = market is None
        breadth_blocked = False
        if market is not None:
            market_regime = market.get("market_regime")
            psa = market.get("pct_above_sma50")
            pct_above_sma50 = float(psa) if psa is not None else None
            if market_regime == "bear_confirmed":
                breadth_blocked = True
            if pct_above_sma50 is not None and pct_above_sma50 < self.min_pct_above_sma50:
                breadth_blocked = True
        if breadth_blocked:
            return None

        # ------------------------------------------------------------------
        # Confluence score (0-100)
        # ------------------------------------------------------------------
        rs_trend = (metrics or {}).get("rs_trend")
        rs_vs_spy = (metrics or {}).get("rs_vs_spy")
        try:
            rs_vs_spy = float(rs_vs_spy) if rs_vs_spy is not None else None
        except (TypeError, ValueError):
            rs_vs_spy = None

        volume_conf_pts = min(rvol / 2.5, 1.0) * 35.0
        if rs_trend == "improving" or (rs_vs_spy is not None and rs_vs_spy > 1.0):
            trend_pts = 25.0
        elif rs_trend == "stable":
            trend_pts = 12.0
        else:
            trend_pts = 0.0
        no_overflow_pts = 20.0  # overflow already rejected above
        divergence_pts = min(divergence_delta / 0.4, 1.0) * 20.0

        score_f = volume_conf_pts + trend_pts + no_overflow_pts + divergence_pts
        score = int(round(max(0.0, min(100.0, score_f))))

        if score < self.min_score:
            return None

        tier = "A" if score >= 70 else "B"   # STRONG -> A, WEAK -> B
        confidence = round(score / 100.0, 4)

        # ------------------------------------------------------------------
        # Entry / stop / target
        # ------------------------------------------------------------------
        atr_14 = float(df["atr_14"].to_numpy()[T])
        atr_14 = atr_14 if np.isfinite(atr_14) else 0.0
        entry = close_t
        structural_stop = min(sweep_low, swing_low) - self.atr_stop_mult * atr_14
        emitted_stop = max(structural_stop, entry * (1 - self.stop_loss_pct / 100.0))
        emitted_tp1 = entry * (1 + self.take_profit_pct / 100.0)
        risk = entry - emitted_stop
        reward = emitted_tp1 - entry
        rr = round(reward / risk, 2) if risk > 0 else 0.0
        structural_tp_3r = entry + 3.0 * (entry - structural_stop)

        cmf20_t = float(df["cmf_20"].to_numpy()[T])
        ts = df["timestamp"].iloc[T] if "timestamp" in df.columns and pd.notna(
            df["timestamp"].iloc[T]) else datetime.now()

        components = {
            "volume_conf": round(volume_conf_pts, 2),
            "trend_rs": round(trend_pts, 2),
            "no_overflow": round(no_overflow_pts, 2),
            "divergence_strength": round(divergence_pts, 2),
        }

        raw_data = {
            "cmf_5": round(float(cmf5[T]), 4) if np.isfinite(cmf5[T]) else None,
            "cmf_20": round(cmf20_t, 4) if np.isfinite(cmf20_t) else None,
            "mfm_t": round(mfm_t, 4),
            "zone_pos": round(zone_pos, 4),
            "swing_low": round(swing_low, 4),
            "sweep_low": round(sweep_low, 4),
            "cmf5_sweep": round(float(cmf5_sweep), 4),
            "cmf5_swinglow": round(float(cmf5_swinglow), 4),
            "divergence_delta": round(divergence_delta, 4),
            "relative_volume": round(rvol, 2),
            "atr_14": round(atr_14, 4),
            "structural_stop": round(structural_stop, 4),
            "structural_tp_3R": round(structural_tp_3r, 4),
            "market_regime": market_regime,
            "pct_above_sma50": pct_above_sma50,
            "breadth_blocked": breadth_blocked,
            "market_context_missing": market_context_missing,
            "overflow_rejected": overflow_rejected,
            "confluence_components": components,
        }

        return SmartMoneyReclaimSignal(
            ticker=ticker,
            signal_type="BUY",
            signal_timestamp=ts,
            entry_price=round(entry, 4),
            stop_loss_price=round(emitted_stop, 4),
            take_profit_price=round(emitted_tp1, 4),
            risk_reward_ratio=rr,
            confidence=confidence,
            quality_tier=tier,
            composite_score=score,
            swing_low=round(swing_low, 4),
            sweep_low=round(sweep_low, 4),
            zone_pos=round(zone_pos, 4),
            cmf_5=round(float(cmf5[T]), 4) if np.isfinite(cmf5[T]) else None,
            cmf_20=round(cmf20_t, 4) if np.isfinite(cmf20_t) else None,
            mfm_t=round(mfm_t, 4),
            divergence_delta=round(divergence_delta, 4),
            relative_volume=round(rvol, 2),
            atr_14=round(atr_14, 4),
            sector=sector,
            raw_data=raw_data,
        )

    def get_config(self) -> Dict[str, Any]:
        return {
            "strategy_name": "SMART_MONEY_RECLAIM",
            "stop_loss_pct": self.stop_loss_pct,
            "take_profit_pct": self.take_profit_pct,
            "cmf_fast": self.CMF_FAST,
            "cmf_slow": self.CMF_SLOW,
            "swing_lookback": self.SWING_LOOKBACK,
            "sweep_window": self.SWEEP_WINDOW,
            "min_volume_conf": self.min_volume_conf,
            "max_zone_pos": self.max_zone_pos,
            "min_pct_above_sma50": self.min_pct_above_sma50,
            "min_score": self.min_score,
        }
