-- Update per-pair scalp SL/TP based on ATR analysis
-- Generated by calculate_optimal_sltp.py

UPDATE smc_simple_pair_overrides
SET scalp_sl_pips = 11.3, scalp_tp_pips = 28.2
WHERE epic = 'CS.D.AUDJPY.MINI.IP';
UPDATE smc_simple_pair_overrides
SET scalp_sl_pips = 5.4, scalp_tp_pips = 13.5
WHERE epic = 'CS.D.AUDUSD.MINI.IP';
UPDATE smc_simple_pair_overrides
SET scalp_sl_pips = 15.5, scalp_tp_pips = 38.8
WHERE epic = 'CS.D.EURJPY.MINI.IP';
UPDATE smc_simple_pair_overrides
SET scalp_sl_pips = 10.2, scalp_tp_pips = 25.5
WHERE epic = 'CS.D.EURUSD.CEEM.IP';
UPDATE smc_simple_pair_overrides
SET scalp_sl_pips = 12.3, scalp_tp_pips = 30.8
WHERE epic = 'CS.D.GBPUSD.MINI.IP';
UPDATE smc_simple_pair_overrides
SET scalp_sl_pips = 6.4, scalp_tp_pips = 16.0
WHERE epic = 'CS.D.NZDUSD.MINI.IP';
UPDATE smc_simple_pair_overrides
SET scalp_sl_pips = 8.0, scalp_tp_pips = 20.0
WHERE epic = 'CS.D.USDCAD.MINI.IP';
UPDATE smc_simple_pair_overrides
SET scalp_sl_pips = 9.3, scalp_tp_pips = 23.2
WHERE epic = 'CS.D.USDCHF.MINI.IP';
UPDATE smc_simple_pair_overrides
SET scalp_sl_pips = 15.2, scalp_tp_pips = 38.0
WHERE epic = 'CS.D.USDJPY.MINI.IP';