# ============================================================================
# SMC SIMPLE STRATEGY CONFIGURATION - ** DEPRECATED **
# ============================================================================
#
# ⚠️ DEPRECATED as of 2026-01-03 - DATABASE IS NOW SOURCE OF TRUTH
#
# This file is NO LONGER the primary configuration source.
# All settings are now stored in the `strategy_config` database:
#   - smc_simple_global_config: Global strategy parameters
#   - smc_simple_pair_overrides: Per-pair customizations
#
# To modify settings, use:
#   1. Streamlit UI: http://localhost:8501 → Scanner Config → SMC Config tab
#   2. Direct SQL: docker exec postgres psql -U postgres -d strategy_config
#
# This file exists ONLY as a fallback when database is unavailable.
# DO NOT EDIT THIS FILE - your changes may be ignored.
#
# ============================================================================
#
# Version: 2.9.0 (Data-Driven Optimization from 85-trade analysis Dec 2025)
# Description: Simplified 3-tier SMC strategy for intraday forex trading
# Architecture:
#   TIER 1: 4H 50 EMA for directional bias
#   TIER 2: 15m swing break with body-close confirmation (was 1H)
#   TIER 3: 5m pullback OR momentum continuation entry
#
# v2.8.1 RELAXED FILTERS (from Rejection Outcome Analysis - 6,032 signals):
#   - MIN_CONFIDENCE_THRESHOLD: 0.50 → 0.48 (CONFIDENCE rejections: 70% WR, +582 pips)
#   - MIN_BODY_PERCENTAGE: 0.35 → 0.20 (6-10% body range: 66% WR, +2,256 pips)
#   - Analysis: Overall rejections had 48.3% WR with +15,624 net pips
#   - IMPACT: Captures more profitable signals that were being over-filtered
#
# v2.8.0 PER-PAIR SESSION OVERRIDES (from 90-day trade_log analysis):
#   - NEW: PAIR_SESSION_OVERRIDES dict for Asian session control per pair
#   - Asian session (21:00-07:00 UTC) outperforms Active hours for 7/9 pairs
#   - ALLOW Asian: USDJPY, USDCHF, EURJPY, EURUSD, AUDUSD, NZDUSD, GBPUSD
#   - BLOCK Asian: AUDJPY, USDCAD (underperform in Asian session)
#   - IMPACT: Recovers ~$5,710 from pairs that perform better in Asian session
#   - Analysis: Asian 50.5% WR (-$684) vs Active 47.7% WR (-$6,131)
#
# v2.7.0 AUDUSD PAIR-SPECIFIC OVERRIDES (from Rejection Outcome Analysis):
#   - NEW: AUDUSD overrides based on 30-day outcome analysis
#   - 844 rejections analyzed: 61% would-be winners (filters too aggressive)
#   - TIER2_SWING: 56.4% win rate, TIER3_PULLBACK: 90.9% win rate
#   - AUDUSD: MIN_BODY_PERCENTAGE 0.35 → 0.25
#   - AUDUSD: MIN_BREAKOUT_ATR_RATIO 0.50 → 0.40
#   - AUDUSD: MOMENTUM_MIN_DEPTH -0.50 → -0.65
#   - AUDUSD: FIB_PULLBACK_MIN 0.236 → 0.18
#   - AUDUSD: MIN_CONFIDENCE_THRESHOLD 0.50 → 0.45
#   - IMPACT: Recovers ~4,446 net pips from over-filtered signals
#
# v2.6.0 EURUSD PAIR-SPECIFIC OVERRIDES:
#   - NEW: PAIR_PARAMETER_OVERRIDES dict for per-pair settings
#   - EURUSD: MIN_BODY_PERCENTAGE 0.35 → 0.25 (smaller candle bodies)
#   - EURUSD: MIN_BREAKOUT_ATR_RATIO 0.50 → 0.40 (smaller breakouts)
#   - EURUSD: MOMENTUM_MIN_DEPTH -0.50 → -0.60 (deeper momentum)
#   - IMPACT: Recovers ~150 signals/week from "Weak breakout body" rejections
#   - All other pairs: unchanged (use default parameters)
#
# v2.4.0 ATR-BASED SL CAP:
#   - PROBLEM: Fixed 55 pip cap was still 7x ATR on low-volatility pairs
#   - ANALYSIS: Trade 1594 (GBPUSD) had 48 pip SL with 7.4 pip ATR = massive risk
#   - ROOT CAUSE: Structural stops + fixed cap ignored current volatility
#   - SOLUTION: Dynamic cap = min(3x ATR, 30 pips absolute)
#   - BENEFIT: SL now proportional to market conditions (22 pips for GBPUSD)
#   - IMPACT: Win rate needed drops from 70%+ to ~50% for breakeven
#
# v2.3.1 CAPPED STRUCTURAL STOPS:
#   - FIX: Structural stops were creating 100+ pip risk on 15m timeframe
#   - ANALYSIS: 89 risk rejections/week (USDJPY avg 111.5 pips, GBPUSD 76.0 pips)
#   - ROOT CAUSE: On 15m, swing structures span wider than on higher TFs
#   - SOLUTION: Cap structural stop at max_risk_after_offset_pips (55 pips)
#   - LOGIC: Use max(structural_stop, max_risk_stop) for BULL, min() for BEAR
#   - TRADE-OFF: Some SLs may be inside swing structure (acceptable for 15m algo)
#   - BENEFIT: Recovers ~90 valid signals/week that were rejected for excess risk
#
# v2.2.0 CONFIDENCE SCORING REDESIGN:
#   - FIX: swing_break_quality was in config but NOT implemented - NOW IMPLEMENTED
#   - FIX: pullback was over-weighted at 40% (25% + 15% fib) - NOW 20%
#   - FIX: volume was binary (15%/5%) - NOW gradient based on spike magnitude
#   - FIX: EMA used fixed 30 pips - NOW ATR-normalized for cross-pair fairness
#   - NEW: Balanced 5-component scoring (each 20% weight)
#   - Expected: +2-4% win rate improvement, better tier alignment
#
# v2.1.0 R:R ROOT CAUSE FIXES:
#   - FIX: Reduced SL_ATR_MULTIPLIER 1.2→1.0 (tighter stops = better R:R)
#   - FIX: Reduced SL_BUFFER_PIPS 8→6 (less buffer = better R:R)
#   - FIX: Reduced pair-specific SL buffers proportionally
#   - FIX: Increased R:R weight in confidence scoring 10%→15%
#   - NEW: Dynamic swing lookback based on ATR volatility
#   - Analysis: 451 R:R rejections were due to inflated SL, not bad setups
#
# v2.0.0 PHASE 3 LIMIT ORDERS:
#   - NEW: Limit order support with intelligent price offsets
#   - v2.2.0: CHANGED to stop-entry style (momentum confirmation)
#   - BUY orders placed ABOVE current price (enter when price breaks up)
#   - SELL orders placed BELOW current price (enter when price breaks down)
#   - Max offset reduced to 3 pips, 15-minute auto-expiry
#
# v1.8.0 PHASE 2 LOGIC ENHANCEMENTS:
#   - NEW: Momentum continuation entry mode (price beyond break = valid)
#   - NEW: ATR-based swing validation (adapts to pair volatility)
#   - NEW: Momentum quality filter (strong breakout candles only)
#   - Target: 45%+ WR, 1.4+ PF (improved from Phase 1's 1.24 PF)
#
# v1.7.0: Phase 1 Quick Fixes - Relaxed parameters (1.24 PF, 39.4% WR)
# v1.6.0: Pullback calculation fix - Timeframe alignment
# v1.5.x: Over-optimized (too restrictive, 80% confidence, 38-62% Fib)
# ============================================================================

from datetime import time

# ============================================================================
# STRATEGY METADATA
# ============================================================================
STRATEGY_NAME = "SMC_SIMPLE"
STRATEGY_VERSION = "2.10.0"
STRATEGY_DATE = "2025-12-30"
STRATEGY_STATUS = "MACD momentum alignment filter: blocks trades against MACD direction"

# ============================================================================
# TIER 1: 4H DIRECTIONAL BIAS (Higher Timeframe)
# ============================================================================
# The 50 EMA is used by institutions for trend direction
# Price above EMA = bullish bias (look for longs only)
# Price below EMA = bearish bias (look for shorts only)

HTF_TIMEFRAME = "4h"                    # Higher timeframe for bias
EMA_PERIOD = 50                          # 50-period EMA (institutional standard)
EMA_BUFFER_PIPS = 2.5                    # v2.3.0: REDUCED from 3 - rejection analysis shows 38 signals lost at 2.0-2.9 pips

# Price position requirements
REQUIRE_CLOSE_BEYOND_EMA = True          # Candle must CLOSE beyond EMA (not just wick)
MIN_DISTANCE_FROM_EMA_PIPS = 3           # v2.1.2: REDUCED from 6 - allow entries 3.5-4.5 pips from EMA

# ============================================================================
# TIER 2: 15M ENTRY TRIGGER (Intermediate Timeframe)
# ============================================================================
# Looking for swing break on 15m as entry confirmation (more frequent than 1H)
# A swing high/low break with BODY CLOSE confirms momentum
# 15m gives 4x more candles than 1H = 4x more break opportunities

TRIGGER_TIMEFRAME = "15m"                # Trigger timeframe (was 1h - too slow)
SWING_LOOKBACK_BARS = 20                 # Base bars to look back for swing detection
SWING_STRENGTH_BARS = 2                  # Bars on each side to confirm swing

# v2.1.0: Dynamic swing lookback based on volatility
# In quiet markets, swings are closer together = use shorter lookback
# In volatile markets, swings are further apart = use longer lookback
# This improves R:R by finding better-spaced swing structures
USE_DYNAMIC_SWING_LOOKBACK = True        # v2.1.0: NEW - adapt lookback to volatility
SWING_LOOKBACK_ATR_LOW = 8               # ATR threshold for low volatility (pips)
SWING_LOOKBACK_ATR_HIGH = 15             # ATR threshold for high volatility (pips)
SWING_LOOKBACK_MIN = 15                  # Minimum lookback bars (quiet market)
SWING_LOOKBACK_MAX = 30                  # Maximum lookback bars (volatile market)

# Body-close confirmation
# NOTE: On 15m timeframe, body-close is too strict - price rarely closes beyond swings
# For 15m trigger, we use wick-based breaks instead (high/low must exceed swing)
REQUIRE_BODY_CLOSE_BREAK = False         # Disabled for 15m - use wick breaks instead
WICK_TOLERANCE_PIPS = 3                  # Tolerance for wick touches

# Volume confirmation
# v1.7.0: RE-ENABLED - improves signal quality without blocking too many
VOLUME_CONFIRMATION_ENABLED = True       # v1.7.0: ENABLED - quality filter
VOLUME_SMA_PERIOD = 20                   # Period for volume moving average
VOLUME_SPIKE_MULTIPLIER = 1.2            # v1.7.0: REDUCED from 1.3 - less strict

# ============================================================================
# TIER 3: 5M EXECUTION (Entry Timeframe)
# ============================================================================
# After 15m break, wait for 5m pullback to Fibonacci zones
# Enter on pullback to get better R:R - 5m gives more precise entries

ENTRY_TIMEFRAME = "5m"                   # Entry/execution timeframe (was 15m)
PULLBACK_ENABLED = True                  # Wait for pullback before entry

# Fibonacci pullback zones (measured from swing to break point)
# v1.7.0: WIDENED - over-tight zones were rejecting valid setups
# v1.5.x: 38%-62% was too restrictive - only 24% band
# Analysis: In trending markets, price often doesn't pull back to golden zone
#           Wider zone catches more valid entries while maintaining quality
FIB_PULLBACK_MIN = 0.236                 # v1.7.0: WIDENED from 0.38 - 23.6% Fib (shallow pullbacks OK)
FIB_PULLBACK_MAX = 0.70                  # v1.7.0: WIDENED from 0.62 - allow deeper pullbacks
FIB_OPTIMAL_ZONE = (0.382, 0.618)        # Golden zone for confidence scoring (not strict filter)

# Pullback timing
MAX_PULLBACK_WAIT_BARS = 12              # Maximum bars to wait for pullback
PULLBACK_CONFIRMATION_BARS = 2           # Bars to confirm pullback

# ============================================================================
# v1.8.0 PHASE 2: MOMENTUM CONTINUATION MODE
# ============================================================================
# Allow entries when price continues beyond break without pullback
# In strong trends, price often doesn't pull back - momentum continuation is valid

MOMENTUM_MODE_ENABLED = True             # v1.8.0: NEW - allow momentum entries
MOMENTUM_MIN_DEPTH = -0.50               # v2.3.0: RELAXED from -0.35 - rejection analysis shows many at -40% to -60%
MOMENTUM_MAX_DEPTH = 0.0                 # 0% = at break point (no pullback yet)
MOMENTUM_CONFIDENCE_PENALTY = 0.05       # Reduce confidence by 5% for momentum entries

# ============================================================================
# v1.8.0 PHASE 2: ATR-BASED SWING VALIDATION
# ============================================================================
# Replace fixed 10-pip minimum swing range with ATR-based threshold
# Adapts to pair volatility (USDCHF has smaller swings than GBPJPY)

USE_ATR_SWING_VALIDATION = True          # v1.8.0: NEW - dynamic swing validation
ATR_PERIOD = 14                          # ATR calculation period
MIN_SWING_ATR_MULTIPLIER = 0.25          # Minimum swing range = 25% of ATR
FALLBACK_MIN_SWING_PIPS = 5              # Absolute minimum if ATR unavailable

# ============================================================================
# v1.8.0 PHASE 2: MOMENTUM QUALITY FILTER
# ============================================================================
# Filter weak breakouts - only enter on strong momentum candles

MOMENTUM_QUALITY_ENABLED = True          # v1.8.0: NEW - filter weak breakouts
MIN_BREAKOUT_ATR_RATIO = 0.5             # Breakout candle range > 50% of ATR
MIN_BODY_PERCENTAGE = 0.20               # v2.8.1: REDUCED from 0.35 - rejection analysis: 6-10% body range had 66% WR (+2,256 pips)

# ============================================================================
# v2.0.0: LIMIT ORDER CONFIGURATION
# ============================================================================
# Use limit orders (pending orders) instead of market orders for better entries
# Place orders at OFFSET from current price to get better fill prices
# Auto-expire unfilled orders after configured time

LIMIT_ORDER_ENABLED = True               # v2.0.0: Enable limit orders
LIMIT_EXPIRY_MINUTES = 45                # v2.8.2: Auto-cancel after 45 min (3 candles on 15m TF) - analysis showed unfilled orders needed more time

# Entry offset configuration (stop-entry style: confirm direction continuation)
# BUY limit ABOVE price, SELL limit BELOW price (momentum confirmation)
# PULLBACK entries: ATR-based offset adapts to volatility
PULLBACK_OFFSET_ATR_FACTOR = 0.2         # Offset = 20% of ATR (reduced for tighter entry)
PULLBACK_OFFSET_MIN_PIPS = 2.0           # Minimum offset: 2 pips
PULLBACK_OFFSET_MAX_PIPS = 3.0           # Maximum offset: 3 pips (user request: reduced from 8)

# MOMENTUM entries: Fixed offset (trend is strong, don't wait too long)
MOMENTUM_OFFSET_PIPS = 3.0               # Fixed 3 pip offset for momentum entries (reduced from 4)

# Risk sanity checks after offset
MIN_RISK_AFTER_OFFSET_PIPS = 5.0         # Reject if SL too close after offset

# v2.4.0: ATR-BASED SL CAP
# Problem: Fixed 55 pip cap was still too large (7x ATR on some pairs)
# Analysis: Trade 1594 had 48 pip SL with only 7.4 pip ATR - massive risk
# Solution: Cap SL at ATR multiple, with hard absolute cap
# Expected: Better risk/reward, ~50% win rate needed vs 70%+ before
MAX_SL_ATR_MULTIPLIER = 3.0              # Maximum SL = 3x ATR (dynamic per pair)
MAX_SL_ABSOLUTE_PIPS = 30.0              # Hard cap regardless of ATR
# Legacy parameter kept for backwards compatibility
MAX_RISK_AFTER_OFFSET_PIPS = 55.0        # Fallback if ATR unavailable

# ============================================================================
# RISK MANAGEMENT
# ============================================================================

# R:R Requirements
# v1.7.0: REDUCED R:R requirements - 2.5 was unrealistic for intraday
# Analysis: Most intraday setups achieve 1.5-2.0 R:R, 2.5+ is too restrictive
MIN_RR_RATIO = 1.5                       # v1.7.0: REDUCED from 2.5 - realistic for intraday
OPTIMAL_RR_RATIO = 2.5                   # v1.7.0: REDUCED from 3.5 - achievable premium setups
MAX_RR_RATIO = 5.0                       # v1.7.0: REDUCED from 6.0 - reasonable cap

# Stop Loss
# v2.1.0: REDUCED buffer and ATR multiplier to improve R:R ratios
# Analysis: 451 R:R rejections (0.01-0.56) were caused by inflated SL distances
# Root cause: SL_BUFFER + ATR_MULTIPLIER combined created 25-30 pip stops
# With tight swings (20 pips), this destroyed R:R (10 reward / 30 risk = 0.33)
# Solution: Tighter stops allow more signals while maintaining edge
SL_BUFFER_PIPS = 6                       # v2.1.0: REDUCED from 8 - tighter stops for better R:R
SL_ATR_MULTIPLIER = 1.0                  # v2.1.0: REDUCED from 1.2 - less ATR inflation
USE_ATR_STOP = True                      # Keep ATR-based adaptive stops

# Take Profit
# v1.7.0: REDUCED minimum TP - 15 pips was rejecting valid tight-structure setups
# Analysis: Rely more on R:R ratio, allow smaller TPs with good R:R
MIN_TP_PIPS = 8                          # v1.7.0: REDUCED from 15 - allow tighter structures
USE_SWING_TARGET = True                  # Target next swing high/low
TP_STRUCTURE_LOOKBACK = 50               # Bars to look for structure targets

# Position sizing (for reference, actual sizing in trade executor)
RISK_PER_TRADE_PCT = 1.0                 # 1% risk per trade

# ============================================================================
# SESSION FILTER
# ============================================================================
# Only trade during high-volume sessions

SESSION_FILTER_ENABLED = True             # v1.4.0: ENABLED - trade only London/NY sessions

# Session definitions (UTC times)
LONDON_SESSION_START = time(7, 0)        # 07:00 UTC
LONDON_SESSION_END = time(16, 0)         # 16:00 UTC
NY_SESSION_START = time(12, 0)           # 12:00 UTC
NY_SESSION_END = time(21, 0)             # 21:00 UTC

# Allowed sessions
ALLOWED_SESSIONS = ['london', 'new_york', 'overlap']
BLOCK_ASIAN_SESSION = True               # Block 21:00-07:00 UTC

# ============================================================================
# v2.8.0: PAIR-SPECIFIC SESSION OVERRIDES (2025-12-28)
# ============================================================================
# Based on 90-day analysis of trade_log, Asian session outperforms Active hours
# for 7 of 9 pairs. Allow Asian trading for profitable pairs, block for losers.
#
# Analysis source: trade_log (90 days, 402 trades)
# - Asian session: 115 trades, -$684, 50.5% WR, avg -$5.95/trade
# - Active hours: 287 trades, -$6,131, 47.7% WR, avg -$21.36/trade
#
PAIR_SESSION_OVERRIDES = {
    # ALLOW Asian session for pairs that outperform Active hours
    'CS.D.USDJPY.MINI.IP': {'allow_asian': True},   # +$1,625 advantage (58.3% vs 32.6% WR)
    'CS.D.USDCHF.MINI.IP': {'allow_asian': True},   # +$2,272 advantage (50.0% vs 31.3% WR)
    'CS.D.EURJPY.MINI.IP': {'allow_asian': True},   # +$381 advantage (56.3% vs 60.0% WR, but +$143 vs -$238)
    'CS.D.EURUSD.CEEM.IP': {'allow_asian': True},   # +$600 advantage
    'CS.D.AUDUSD.MINI.IP': {'allow_asian': True},   # +$298 advantage (55.6% vs 45.5% WR)
    'CS.D.NZDUSD.MINI.IP': {'allow_asian': True},   # +$279 advantage (58.3% vs 42.9% WR)
    'CS.D.GBPUSD.MINI.IP': {'allow_asian': True},   # +$254 advantage (57.1% vs 60.6% WR, but -$180 vs -$434)

    # KEEP Asian block for pairs that underperform Active hours
    'CS.D.AUDJPY.MINI.IP': {'allow_asian': False},  # -$38 disadvantage (33.3% vs 50.0% WR)
    'CS.D.USDCAD.MINI.IP': {'allow_asian': False},  # -$225 disadvantage (42.9% vs 58.3% WR)
}

def is_asian_session_allowed(epic: str) -> bool:
    """
    Check if Asian session trading is allowed for a specific pair.

    Args:
        epic: The trading pair epic (e.g., 'CS.D.USDJPY.MINI.IP')

    Returns:
        True if Asian session is allowed for this pair, False otherwise
    """
    override = PAIR_SESSION_OVERRIDES.get(epic)
    if override is not None:
        return override.get('allow_asian', not BLOCK_ASIAN_SESSION)

    # Default to global BLOCK_ASIAN_SESSION setting
    return not BLOCK_ASIAN_SESSION

# ============================================================================
# SIGNAL LIMITS
# ============================================================================

# DEPRECATED in v3.0.0: MAX_SIGNALS_PER_PAIR_PER_DAY was never enforced in code
# Signal frequency is now managed by the adaptive cooldown system below

MAX_CONCURRENT_SIGNALS = 3               # Maximum concurrent open signals
SIGNAL_COOLDOWN_HOURS = 3                # Fallback when ADAPTIVE_COOLDOWN_ENABLED=False

# ============================================================================
# v3.0.0: ADAPTIVE COOLDOWN SYSTEM
# ============================================================================
# Dynamic cooldown based on trade outcomes, win rates, and market context.
# Replaces static cooldown with intelligent, context-aware timing.

ADAPTIVE_COOLDOWN_ENABLED = True         # Enable adaptive cooldown (False = use static SIGNAL_COOLDOWN_HOURS)

# Base cooldown (starting point before adjustments)
BASE_COOLDOWN_HOURS = 2.0                # Base cooldown before adjustments

# Trade outcome multipliers
COOLDOWN_AFTER_WIN_MULTIPLIER = 0.5      # Reduce cooldown by 50% after a winning trade
COOLDOWN_AFTER_LOSS_MULTIPLIER = 1.5     # Increase cooldown by 50% after a losing trade

# Consecutive loss handling
CONSECUTIVE_LOSS_PENALTY_HOURS = 1.0     # Add 1 hour per consecutive loss on same pair
MAX_CONSECUTIVE_LOSSES_BEFORE_BLOCK = 3  # Block pair entirely after 3 consecutive losses
CONSECUTIVE_LOSS_BLOCK_HOURS = 8.0       # Block duration after max consecutive losses

# Win rate-based adjustments (rolling window of recent trades)
WIN_RATE_LOOKBACK_TRADES = 20            # Number of trades to calculate rolling win rate
HIGH_WIN_RATE_THRESHOLD = 0.60           # 60%+ win rate = high performer
LOW_WIN_RATE_THRESHOLD = 0.40            # Below 40% = poor performer
CRITICAL_WIN_RATE_THRESHOLD = 0.30       # Below 30% = consider blocking

HIGH_WIN_RATE_COOLDOWN_REDUCTION = 0.25  # Reduce cooldown by 25% for high win rate pairs
LOW_WIN_RATE_COOLDOWN_INCREASE = 0.50    # Increase cooldown by 50% for low win rate pairs

# Market context adjustments
HIGH_VOLATILITY_ATR_MULTIPLIER = 1.5     # ATR > 1.5x 20-period average = high volatility
VOLATILITY_COOLDOWN_ADJUSTMENT = 0.30    # +30% cooldown during high volatility
STRONG_TREND_COOLDOWN_REDUCTION = 0.30   # -30% cooldown when strong EMA trend alignment

# Session-based adjustments
SESSION_CHANGE_RESET_COOLDOWN = True     # Reset cooldown on session change (london→new_york)

# Absolute bounds (safety limits)
MIN_COOLDOWN_HOURS = 1.0                 # Never less than 1 hour
MAX_COOLDOWN_HOURS = 12.0                # Never more than 12 hours

# ============================================================================
# PAIR CONFIGURATION
# ============================================================================

# Enabled pairs (major forex pairs with good liquidity)
# v2.9.0: USDCHF DISABLED - 11% win rate, -$142 avg loss, -$1,278 total (Dec 2025 analysis)
ENABLED_PAIRS = [
    'CS.D.EURUSD.CEEM.IP',  # CEEM uses scaled pricing (11646 instead of 1.1646)
    'CS.D.GBPUSD.MINI.IP',
    'CS.D.USDJPY.MINI.IP',
    # 'CS.D.USDCHF.MINI.IP',  # DISABLED v2.9.0: 11% WR, -$142 avg, worst performer
    'CS.D.AUDUSD.MINI.IP',
    'CS.D.USDCAD.MINI.IP',
    'CS.D.NZDUSD.MINI.IP',
    'CS.D.EURJPY.MINI.IP',
    # 'CS.D.GBPJPY.MINI.IP',  # No data in 85-trade analysis - disabled until analyzed
    'CS.D.AUDJPY.MINI.IP',  # 53% WR - requires volume filter 0.60
]

# Pair-specific pip values (from existing config)
PAIR_PIP_VALUES = {
    'CS.D.EURUSD.CEEM.IP': 1.0,  # CEEM uses scaled pricing, 1 pip = 1 point
    'CS.D.GBPUSD.MINI.IP': 0.0001,
    'CS.D.USDJPY.MINI.IP': 0.01,
    'CS.D.USDCHF.MINI.IP': 0.0001,
    'CS.D.AUDUSD.MINI.IP': 0.0001,
    'CS.D.USDCAD.MINI.IP': 0.0001,
    'CS.D.NZDUSD.MINI.IP': 0.0001,
    'CS.D.EURJPY.MINI.IP': 0.01,
    'CS.D.GBPJPY.MINI.IP': 0.01,
    'CS.D.AUDJPY.MINI.IP': 0.01,
}

# ============================================================================
# v2.1.0: PAIR-SPECIFIC SL BUFFERS (REDUCED)
# ============================================================================
# Override default SL_BUFFER_PIPS for specific pairs based on volatility
# v2.1.0: REDUCED all buffers by ~25% to improve R:R ratios
# Analysis: Large buffers were main cause of R:R rejections (0.01-0.56 values)

PAIR_SL_BUFFERS = {
    # Low volatility / low liquidity pairs
    'USDCHF': 9,            # v2.1.0: REDUCED from 12 (still accounts for spreads)
    'CS.D.USDCHF.MINI.IP': 9,

    # JPY crosses are volatile - but tighter stops improve R:R
    'AUDJPY': 12,           # v2.1.0: REDUCED from 15
    'CS.D.AUDJPY.MINI.IP': 12,
    'EURJPY': 14,           # v2.1.0: REDUCED from 18
    'CS.D.EURJPY.MINI.IP': 14,
    'GBPJPY': 14,           # v2.1.0: REDUCED from 18
    'CS.D.GBPJPY.MINI.IP': 14,
    'USDJPY': 9,            # v2.1.0: REDUCED from 12
    'CS.D.USDJPY.MINI.IP': 9,

    # Commodity currencies
    'USDCAD': 8,            # v2.1.0: REDUCED from 10
    'CS.D.USDCAD.MINI.IP': 8,

    # Cable
    'GBPUSD': 8,            # v2.1.0: REDUCED from 10
    'CS.D.GBPUSD.MINI.IP': 8,

    # Default for majors (EURUSD, AUDUSD, NZDUSD) = SL_BUFFER_PIPS (6)
}

# ============================================================================
# v1.9.0: PAIR-SPECIFIC CONFIDENCE FLOORS
# ============================================================================
# Higher confidence required for volatile / difficult pairs
# v2.9.0: Aligned with global MIN_CONFIDENCE_THRESHOLD = 0.48
# Note: USDJPY has higher threshold (0.52) via PAIR_PARAMETER_OVERRIDES

PAIR_MIN_CONFIDENCE = {
    # v2.9.0: Use global 0.48 for most pairs (rounding fix handles edge cases)
    # Pair-specific overrides in PAIR_PARAMETER_OVERRIDES take precedence

    # JPY crosses - use global threshold
    'EURJPY': 0.48,
    'CS.D.EURJPY.MINI.IP': 0.48,
    'GBPJPY': 0.48,
    'CS.D.GBPJPY.MINI.IP': 0.48,
    'AUDJPY': 0.48,
    'CS.D.AUDJPY.MINI.IP': 0.48,

    # USDCHF - disabled entirely in ENABLED_PAIRS
    'USDCHF': 0.48,
    'CS.D.USDCHF.MINI.IP': 0.48,

    # Default for others = MIN_CONFIDENCE_THRESHOLD (0.48)
}

# ============================================================================
# v2.11.0: VOLUME-ADJUSTED CONFIDENCE THRESHOLDS (Per-Pair)
# ============================================================================
# Data-driven analysis from 30-day rejection outcomes (Dec 2025):
#
# KEY FINDING: High volume (>=0.7) CONFIDENCE rejections show dramatically
# different win rates by pair:
#
# | Pair   | High Vol WR | Low Vol WR | Recommendation                    |
# |--------|-------------|------------|-----------------------------------|
# | AUDUSD | 100%        | 100%       | Lower threshold to 0.45 @ vol>=0.7|
# | NZDUSD | 100%        | 100%       | Lower threshold to 0.45 @ vol>=0.7|
# | EURJPY | 0%          | 11%        | KEEP strict - volume doesn't help |
#
# When volume_ratio >= HIGH_VOLUME_THRESHOLD, use reduced confidence floor.
# This allows high-probability setups through when volume confirms the move.
#
HIGH_VOLUME_THRESHOLD = 0.70            # Volume ratio considered "high"
VOLUME_ADJUSTED_CONFIDENCE_ENABLED = True

# Per-pair confidence when volume >= HIGH_VOLUME_THRESHOLD
# Format: 'PAIR': confidence_threshold_when_high_volume
# If pair not listed, uses standard PAIR_MIN_CONFIDENCE (no volume adjustment)
PAIR_HIGH_VOLUME_CONFIDENCE = {
    # AUDUSD: 100% WR on high-vol CONFIDENCE rejections - lower threshold
    'AUDUSD': 0.45,
    'CS.D.AUDUSD.MINI.IP': 0.45,

    # NZDUSD: 100% WR on high-vol CONFIDENCE rejections - lower threshold
    'NZDUSD': 0.45,
    'CS.D.NZDUSD.MINI.IP': 0.45,

    # EURUSD: Test with moderate reduction (needs more data)
    'EURUSD': 0.46,
    'CS.D.EURUSD.CEEM.IP': 0.46,
    'CS.D.EURUSD.MINI.IP': 0.46,

    # GBPUSD: Test with moderate reduction (needs more data)
    'GBPUSD': 0.46,
    'CS.D.GBPUSD.MINI.IP': 0.46,

    # JPY pairs - NO volume adjustment (EURJPY showed 0% WR even with high volume)
    # These pairs are explicitly NOT listed = use standard threshold regardless of volume
    # 'EURJPY': DO NOT ADD - high volume didn't help win rate
    # 'GBPJPY': DO NOT ADD - insufficient data, keep conservative
    # 'USDJPY': DO NOT ADD - insufficient data, keep conservative
    # 'AUDJPY': DO NOT ADD - insufficient data, keep conservative
}

# ============================================================================
# v2.11.0: ATR-ADJUSTED CONFIDENCE THRESHOLDS (Per-Pair)
# ============================================================================
# Data-driven analysis from 30-day rejection outcomes (Dec 2025):
#
# CRITICAL FINDING: ATR level at rejection dramatically affects outcome:
#
# | ATR Level              | CONFIDENCE Win Rate | Sample     |
# |------------------------|---------------------|------------|
# | LOW (<0.0004)          | 100% (42W/0L)       | ALL winners missed! |
# | MEDIUM (0.0004-0.0008) | 100% (8W/0L)        | ALL winners missed! |
# | HIGH (>=0.0008)        | 8.3% (2W/22L)       | Correctly rejected  |
#
# Per-pair breakdown:
# | Pair   | ATR   | Win Rate | Action                          |
# |--------|-------|----------|----------------------------------|
# | AUDUSD | LOW   | 100%     | Lower threshold in calm markets  |
# | NZDUSD | LOW   | 100%     | Lower threshold in calm markets  |
# | EURJPY | HIGH  | 8.3%     | Keep strict in volatile markets  |
#
# LOGIC: In calm markets (low ATR), price moves are more predictable,
#        so lower confidence signals still have high win rates.
#        In volatile markets (high ATR), require higher confidence.
#
LOW_ATR_THRESHOLD = 0.0004              # ATR below this = "calm market"
HIGH_ATR_THRESHOLD = 0.0008             # ATR above this = "volatile market"
ATR_ADJUSTED_CONFIDENCE_ENABLED = True

# Per-pair confidence when ATR < LOW_ATR_THRESHOLD (calm market)
# Format: 'PAIR': confidence_threshold_in_calm_market
# If pair not listed, uses standard PAIR_MIN_CONFIDENCE (no ATR adjustment)
PAIR_LOW_ATR_CONFIDENCE = {
    # AUDUSD: 100% WR on low-ATR CONFIDENCE rejections - lower threshold
    'AUDUSD': 0.44,
    'CS.D.AUDUSD.MINI.IP': 0.44,

    # NZDUSD: 100% WR on low-ATR CONFIDENCE rejections - lower threshold
    'NZDUSD': 0.44,
    'CS.D.NZDUSD.MINI.IP': 0.44,

    # EURUSD: Test with moderate reduction (needs more data)
    'EURUSD': 0.45,
    'CS.D.EURUSD.CEEM.IP': 0.45,
    'CS.D.EURUSD.MINI.IP': 0.45,

    # GBPUSD: Test with moderate reduction (needs more data)
    'GBPUSD': 0.45,
    'CS.D.GBPUSD.MINI.IP': 0.45,

    # JPY pairs - NO ATR adjustment (EURJPY showed 8.3% WR even in low ATR context)
    # These pairs are explicitly NOT listed = use standard threshold regardless of ATR
    # 'EURJPY': DO NOT ADD - high ATR correlates with losses
    # 'GBPJPY': DO NOT ADD - insufficient data, keep conservative
    # 'USDJPY': DO NOT ADD - insufficient data, keep conservative
    # 'AUDJPY': DO NOT ADD - insufficient data, keep conservative
}

# Per-pair confidence when ATR >= HIGH_ATR_THRESHOLD (volatile market)
# INCREASE threshold for volatile conditions to be more selective
PAIR_HIGH_ATR_CONFIDENCE = {
    # EURJPY: 8.3% WR in high ATR - INCREASE threshold to block more
    'EURJPY': 0.52,
    'CS.D.EURJPY.MINI.IP': 0.52,

    # Other JPY pairs - be more cautious in high volatility
    'GBPJPY': 0.52,
    'CS.D.GBPJPY.MINI.IP': 0.52,
    'USDJPY': 0.52,
    'CS.D.USDJPY.MINI.IP': 0.52,
    'AUDJPY': 0.52,
    'CS.D.AUDJPY.MINI.IP': 0.52,

    # Major pairs - slight increase in volatile conditions
    'EURUSD': 0.50,
    'CS.D.EURUSD.CEEM.IP': 0.50,
    'CS.D.EURUSD.MINI.IP': 0.50,
    'GBPUSD': 0.50,
    'CS.D.GBPUSD.MINI.IP': 0.50,

    # AUDUSD/NZDUSD - keep standard threshold even in high ATR (not enough data)
    # Not listed = use standard threshold
}

# ============================================================================
# v2.11.0: EMA DISTANCE-ADJUSTED CONFIDENCE THRESHOLDS (Per-Pair)
# ============================================================================
# Data-driven analysis from 30-day rejection outcomes (Dec 2025):
#
# CRITICAL FINDING: EMA distance dramatically affects CONFIDENCE rejection outcomes:
#
# | EMA Zone          | CONFIDENCE Win Rate | Sample     |
# |-------------------|---------------------|------------|
# | NEAR (<20 pips)   | 100% (42W/0L)       | ALL winners missed! |
# | MEDIUM (20-30)    | 44.4% (8W/10L)      | Borderline          |
# | FAR (30-40)       | 0% (0W/6L)          | Correctly rejected  |
# | EXTENDED (40+)    | 25% (2W/6L)         | Correctly rejected  |
#
# Per-pair breakdown:
# | Pair   | EMA Zone   | Win Rate | Action                         |
# |--------|------------|----------|--------------------------------|
# | AUDUSD | NEAR <20   | 100%     | Lower threshold near EMA       |
# | AUDUSD | MEDIUM     | 100%     | Lower threshold medium EMA     |
# | NZDUSD | NEAR <20   | 100%     | Lower threshold near EMA       |
# | EURJPY | MEDIUM     | 0%       | INCREASE threshold             |
# | EURJPY | FAR 30+    | 14%      | INCREASE threshold             |
#
# LOGIC: Signals near the EMA (price aligned with trend) are higher probability.
#        Signals far from EMA (overextended) are lower probability.
#
NEAR_EMA_THRESHOLD_PIPS = 20            # Below this = "near EMA" (trend-aligned)
FAR_EMA_THRESHOLD_PIPS = 30             # Above this = "far from EMA" (extended)
EMA_DISTANCE_ADJUSTED_CONFIDENCE_ENABLED = True

# Per-pair confidence when EMA distance < NEAR_EMA_THRESHOLD_PIPS (trend-aligned)
# Format: 'PAIR': confidence_threshold_when_near_ema
# If pair not listed, uses standard PAIR_MIN_CONFIDENCE (no EMA adjustment)
PAIR_NEAR_EMA_CONFIDENCE = {
    # AUDUSD: 100% WR on NEAR EMA CONFIDENCE rejections - lower threshold
    'AUDUSD': 0.44,
    'CS.D.AUDUSD.MINI.IP': 0.44,

    # NZDUSD: 100% WR on NEAR EMA CONFIDENCE rejections - lower threshold
    'NZDUSD': 0.44,
    'CS.D.NZDUSD.MINI.IP': 0.44,

    # EURUSD: Test with moderate reduction (needs more data)
    'EURUSD': 0.45,
    'CS.D.EURUSD.CEEM.IP': 0.45,
    'CS.D.EURUSD.MINI.IP': 0.45,

    # GBPUSD: Test with moderate reduction (needs more data)
    'GBPUSD': 0.45,
    'CS.D.GBPUSD.MINI.IP': 0.45,

    # JPY pairs - NO EMA distance adjustment (EURJPY still had 0% WR near EMA)
    # These pairs are explicitly NOT listed = use standard threshold
}

# Per-pair confidence when EMA distance >= FAR_EMA_THRESHOLD_PIPS (overextended)
# INCREASE threshold for extended conditions - need more confidence when chasing
PAIR_FAR_EMA_CONFIDENCE = {
    # EURJPY: 0% WR at MEDIUM, 14% at FAR - INCREASE threshold significantly
    'EURJPY': 0.55,
    'CS.D.EURJPY.MINI.IP': 0.55,

    # Other JPY pairs - be more cautious when extended from EMA
    'GBPJPY': 0.52,
    'CS.D.GBPJPY.MINI.IP': 0.52,
    'USDJPY': 0.52,
    'CS.D.USDJPY.MINI.IP': 0.52,
    'AUDJPY': 0.52,
    'CS.D.AUDJPY.MINI.IP': 0.52,

    # Major pairs - slight increase when overextended
    'EURUSD': 0.50,
    'CS.D.EURUSD.CEEM.IP': 0.50,
    'CS.D.EURUSD.MINI.IP': 0.50,
    'GBPUSD': 0.50,
    'CS.D.GBPUSD.MINI.IP': 0.50,

    # AUDUSD/NZDUSD - keep standard threshold even when extended (100% WR at medium)
    # Not listed = use standard threshold
}

# ============================================================================
# v2.5.0: PAIR-SPECIFIC BLOCKING CONDITIONS
# ============================================================================
# Block signals for specific pairs when certain unfavorable conditions combine.
# Based on analysis of live trading outcomes showing consistent losses.
#
# USDCHF Analysis (Trade 1620, Alert 6562):
#   - 139 closed trades, 26.62% win rate, -$4,917.77 total P&L (worst pair)
#   - Avg loss: -$54.04 per trade
#   - High EMA distance (>60 pips): 0% win rate, -$515 loss
#   - No volume confirmation: 0% win rate, -$1,031 loss
#   - Not in optimal zone: 25% win rate, -$480 loss
#   - Combined bad conditions: 0% win rate
#
# These blocking conditions use tier2_swing.volume_confirmed from strategy_indicators
# (NOT the top-level volume_confirmation column which is always false for SMC_SIMPLE)

PAIR_BLOCKING_CONDITIONS = {
    # USDCHF: Block when multiple weak factors combine
    # This pair has the worst performance (-$4,917) and needs strict filtering
    'CS.D.USDCHF.MINI.IP': {
        'enabled': True,
        'description': 'Block USDCHF on weak setups - worst performing pair',
        'conditions': {
            # Block when EMA distance is too extended (price has moved too far)
            'max_ema_distance_pips': 60.0,  # >60 pips from 4H EMA = 0% win rate

            # Require volume confirmation for this pair (normally optional)
            'require_volume_confirmation': True,  # No volume = 0% win rate

            # Block momentum entries (negative pullback) without volume
            'block_momentum_without_volume': True,

            # Require optimal zone entry for this difficult pair
            'require_optimal_zone': False,  # Set True to be more strict

            # Minimum confidence override for this pair
            'min_confidence_override': 0.60,  # Higher than default 0.50
        },
        'blocking_logic': 'any',  # 'any' = block if ANY condition fails, 'all' = block only if ALL fail
    },

    # USDCHF alternative epic format
    'USDCHF': {
        'enabled': True,
        'description': 'Block USDCHF on weak setups - worst performing pair',
        'conditions': {
            'max_ema_distance_pips': 60.0,
            'require_volume_confirmation': True,
            'block_momentum_without_volume': True,
            'require_optimal_zone': False,
            'min_confidence_override': 0.60,
        },
        'blocking_logic': 'any',
    },

    # Template for other pairs (disabled by default)
    # Copy and modify for pairs showing consistent losses
    # 'CS.D.EURJPY.MINI.IP': {
    #     'enabled': False,
    #     'description': 'Template - not active',
    #     'conditions': {
    #         'max_ema_distance_pips': 80.0,
    #         'require_volume_confirmation': False,
    #         'block_momentum_without_volume': False,
    #         'require_optimal_zone': False,
    #         'min_confidence_override': None,
    #     },
    #     'blocking_logic': 'any',
    # },
}

def should_block_signal(epic: str, signal_data: dict) -> tuple[bool, str]:
    """
    Check if a signal should be blocked based on pair-specific conditions.

    Args:
        epic: The trading pair epic (e.g., 'CS.D.USDCHF.MINI.IP')
        signal_data: Dict containing signal details with keys:
            - ema_distance_pips: float - Distance from 4H EMA in pips
            - volume_confirmed: bool - Whether volume spike was confirmed
            - in_optimal_zone: bool - Whether entry is in Fib optimal zone
            - pullback_depth: float - Pullback percentage (negative = momentum)
            - confidence_score: float - Overall confidence score

    Returns:
        Tuple of (should_block: bool, reason: str)
    """
    # Check if pair has blocking conditions configured
    config = PAIR_BLOCKING_CONDITIONS.get(epic)
    if not config or not config.get('enabled', False):
        return False, ""

    conditions = config.get('conditions', {})
    blocking_logic = config.get('blocking_logic', 'any')

    block_reasons = []

    # Check EMA distance
    max_ema = conditions.get('max_ema_distance_pips')
    if max_ema is not None:
        ema_distance = signal_data.get('ema_distance_pips', 0)
        if ema_distance > max_ema:
            block_reasons.append(f"EMA distance {ema_distance:.1f} > {max_ema} pips")

    # Check volume confirmation
    if conditions.get('require_volume_confirmation', False):
        volume_confirmed = signal_data.get('volume_confirmed', False)
        if not volume_confirmed:
            block_reasons.append("No volume confirmation (required for this pair)")

    # Check momentum without volume
    if conditions.get('block_momentum_without_volume', False):
        pullback_depth = signal_data.get('pullback_depth', 0)
        volume_confirmed = signal_data.get('volume_confirmed', False)
        if pullback_depth < 0 and not volume_confirmed:
            block_reasons.append(f"Momentum entry (pullback {pullback_depth:.1%}) without volume")

    # Check optimal zone requirement
    if conditions.get('require_optimal_zone', False):
        in_optimal = signal_data.get('in_optimal_zone', False)
        if not in_optimal:
            block_reasons.append("Not in optimal Fib zone (required for this pair)")

    # Check confidence override
    min_conf = conditions.get('min_confidence_override')
    if min_conf is not None:
        confidence = signal_data.get('confidence_score', 0)
        if confidence < min_conf:
            block_reasons.append(f"Confidence {confidence:.1%} < {min_conf:.1%} minimum for this pair")

    # Determine if signal should be blocked
    if blocking_logic == 'any' and block_reasons:
        return True, f"Blocked: {'; '.join(block_reasons)}"
    elif blocking_logic == 'all' and len(block_reasons) == len([c for c in conditions.values() if c]):
        return True, f"Blocked (all conditions failed): {'; '.join(block_reasons)}"

    return False, ""

# ============================================================================
# v2.6.0: PAIR-SPECIFIC PARAMETER OVERRIDES
# ============================================================================
# Override default strategy parameters for specific pairs.
# Only EURUSD is configured - all other pairs use default values.
#
# EURUSD Analysis (7-day rejection data):
#   - 740 TIER2_SWING rejections, mostly "Weak breakout body (6-35% < 35%)"
#   - EURUSD has smaller-bodied candles than GBP/JPY pairs
#   - Reducing MIN_BODY_PERCENTAGE from 0.35 to 0.25 recovers ~150 signals

PAIR_PARAMETER_OVERRIDES = {
    # ============================================================================
    # v2.9.0: DATA-DRIVEN PAIR-SPECIFIC OVERRIDES (Dec 2025 - 85 trade analysis)
    # ============================================================================
    # Analysis methodology:
    #   - 85 closed SMC_SIMPLE trades (Dec 1-30, 2025)
    #   - Winners vs Losers comparison per epic
    #   - Volume ratio and confidence score correlation analysis
    #
    # Key findings:
    #   - Volume >= 0.50: 70%+ win rate vs 43% without
    #   - Confidence > 0.75: 42% win rate (paradox - higher = worse)
    #   - USDCHF: 11% WR - DISABLED entirely
    # ============================================================================

    # ============================================================================
    # TOP PERFORMERS - Keep relaxed settings (60%+ win rate)
    # ============================================================================

    'CS.D.AUDUSD.MINI.IP': {
        'enabled': True,
        'description': 'AUDUSD - TOP PERFORMER 71% WR, keep relaxed settings',
        'overrides': {
            # Keep existing relaxed settings - they're working
            'MIN_BODY_PERCENTAGE': 0.20,
            'MIN_BREAKOUT_ATR_RATIO': 0.40,
            'MOMENTUM_MIN_DEPTH': -0.65,
            'FIB_PULLBACK_MIN': 0.18,
            'MIN_CONFIDENCE_THRESHOLD': 0.45,
            # No volume filter - winners avg 0.49, losers avg 0.74 (paradox for this pair)
            'MIN_VOLUME_RATIO': 0.0,
        },
    },
    'AUDUSD': {
        'enabled': True,
        'description': 'AUDUSD - TOP PERFORMER 71% WR',
        'overrides': {
            'MIN_BODY_PERCENTAGE': 0.20,
            'MIN_BREAKOUT_ATR_RATIO': 0.40,
            'MOMENTUM_MIN_DEPTH': -0.65,
            'FIB_PULLBACK_MIN': 0.18,
            'MIN_CONFIDENCE_THRESHOLD': 0.45,
            'MIN_VOLUME_RATIO': 0.0,
        },
    },

    'CS.D.EURJPY.MINI.IP': {
        'enabled': True,
        'description': 'EURJPY - 64% WR, volume is KEY differentiator (W:0.67 vs L:0.25)',
        'overrides': {
            'MIN_VOLUME_RATIO': 0.50,  # Winners 0.67 vs Losers 0.25
        },
    },
    'EURJPY': {
        'enabled': True,
        'description': 'EURJPY - 64% WR, volume is KEY',
        'overrides': {
            'MIN_VOLUME_RATIO': 0.50,
        },
    },

    'CS.D.GBPUSD.MINI.IP': {
        'enabled': True,
        'description': 'GBPUSD - 63% WR, keep defaults',
        'overrides': {},  # Use global defaults - working well
    },
    'GBPUSD': {
        'enabled': True,
        'description': 'GBPUSD - 63% WR, keep defaults',
        'overrides': {},
    },

    'CS.D.USDCAD.MINI.IP': {
        'enabled': True,
        'description': 'USDCAD - 63% WR, high volume pairs win (W:0.85 vs L:1.10)',
        'overrides': {
            'MIN_VOLUME_RATIO': 0.50,
        },
    },
    'USDCAD': {
        'enabled': True,
        'description': 'USDCAD - 63% WR, high volume pairs win',
        'overrides': {
            'MIN_VOLUME_RATIO': 0.50,
        },
    },

    # ============================================================================
    # MODERATE PERFORMERS - Tighten volume filter (50-60% win rate)
    # ============================================================================

    'CS.D.AUDJPY.MINI.IP': {
        'enabled': True,
        'description': 'AUDJPY - 53% WR, VOLUME IS CRITICAL (W:0.78 vs L:0.19)',
        'overrides': {
            'MIN_VOLUME_RATIO': 0.60,  # Winners 0.78 vs Losers 0.19 - HUGE gap
        },
    },
    'AUDJPY': {
        'enabled': True,
        'description': 'AUDJPY - 53% WR, VOLUME IS CRITICAL',
        'overrides': {
            'MIN_VOLUME_RATIO': 0.60,
        },
    },

    # ============================================================================
    # UNDERPERFORMERS - Strict filters (< 50% win rate)
    # ============================================================================

    'CS.D.EURUSD.CEEM.IP': {
        'enabled': True,
        'description': 'EURUSD - 43% WR, HIGH confidence = LOSSES (W:0.68 vs L:0.75)',
        'overrides': {
            'MIN_BODY_PERCENTAGE': 0.25,        # Tighten from 0.20
            'MIN_BREAKOUT_ATR_RATIO': 0.50,     # Tighten from 0.40
            'MOMENTUM_MIN_DEPTH': -0.45,        # Tighten from -0.60
            'MAX_CONFIDENCE_THRESHOLD': 0.70,   # Winners 0.68 vs Losers 0.75
            'MIN_VOLUME_RATIO': 0.40,           # Losers avg 0.42
        },
    },
    'EURUSD': {
        'enabled': True,
        'description': 'EURUSD - 43% WR, HIGH confidence = LOSSES',
        'overrides': {
            'MIN_BODY_PERCENTAGE': 0.25,
            'MIN_BREAKOUT_ATR_RATIO': 0.50,
            'MOMENTUM_MIN_DEPTH': -0.45,
            'MAX_CONFIDENCE_THRESHOLD': 0.70,
            'MIN_VOLUME_RATIO': 0.40,
        },
    },

    'CS.D.NZDUSD.MINI.IP': {
        'enabled': True,
        'description': 'NZDUSD - 43% WR, tighten filters (W:0.63 conf vs L:0.73)',
        'overrides': {
            'MIN_BODY_PERCENTAGE': 0.25,        # Tighten
            'MIN_BREAKOUT_ATR_RATIO': 0.50,     # Tighten from 0.45
            'MAX_CONFIDENCE_THRESHOLD': 0.70,   # Winners 0.63 vs Losers 0.73
            'MIN_VOLUME_RATIO': 0.35,           # Winners 0.39 vs Losers 0.14
        },
    },
    'NZDUSD': {
        'enabled': True,
        'description': 'NZDUSD - 43% WR, tighten filters',
        'overrides': {
            'MIN_BODY_PERCENTAGE': 0.25,
            'MIN_BREAKOUT_ATR_RATIO': 0.50,
            'MAX_CONFIDENCE_THRESHOLD': 0.70,
            'MIN_VOLUME_RATIO': 0.35,
        },
    },

    'CS.D.USDJPY.MINI.IP': {
        'enabled': True,
        'description': 'USDJPY - 38% WR, most conservative settings needed',
        'overrides': {
            'MIN_BODY_PERCENTAGE': 0.30,        # Strict
            'MIN_BREAKOUT_ATR_RATIO': 0.55,     # Strict
            'MOMENTUM_MIN_DEPTH': -0.40,        # Less aggressive momentum
            'FIB_PULLBACK_MIN': 0.30,           # Wait for deeper pullback
            'MAX_CONFIDENCE_THRESHOLD': 0.70,   # Cap confidence
            'MIN_VOLUME_RATIO': 0.40,           # Volume doesn't help much here
            'MIN_CONFIDENCE_THRESHOLD': 0.52,   # Slightly higher floor
        },
    },
    'USDJPY': {
        'enabled': True,
        'description': 'USDJPY - 38% WR, most conservative settings',
        'overrides': {
            'MIN_BODY_PERCENTAGE': 0.30,
            'MIN_BREAKOUT_ATR_RATIO': 0.55,
            'MOMENTUM_MIN_DEPTH': -0.40,
            'FIB_PULLBACK_MIN': 0.30,
            'MAX_CONFIDENCE_THRESHOLD': 0.70,
            'MIN_VOLUME_RATIO': 0.40,
            'MIN_CONFIDENCE_THRESHOLD': 0.52,
        },
    },

    # ============================================================================
    # DISABLED PAIRS (tracked here for reference)
    # ============================================================================
    # USDCHF: REMOVED from ENABLED_PAIRS - 11% WR, -$142 avg, -$1,278 total
    # Do not add overrides here as the pair is completely disabled
}

def get_pair_parameter(epic: str, param_name: str, default_value):
    """
    Get parameter value with pair-specific override if configured.

    Args:
        epic: The trading pair epic (e.g., 'CS.D.EURUSD.CEEM.IP')
        param_name: The parameter name to look up (e.g., 'MIN_BODY_PERCENTAGE')
        default_value: The default value to return if no override exists

    Returns:
        The overridden value if configured, otherwise the default value
    """
    config = PAIR_PARAMETER_OVERRIDES.get(epic)
    if config and config.get('enabled', False):
        overrides = config.get('overrides', {})
        if param_name in overrides:
            return overrides[param_name]
    return default_value

# ============================================================================
# CONFIDENCE SCORING
# ============================================================================
# v2.2.0: Redesigned confidence scoring with proper tier alignment
# Fixed issues: swing_break_quality was in config but NOT implemented,
#               pullback was over-weighted at 40% (25% + 15% fib_accuracy)

# Confidence thresholds
# v1.7.0: REDUCED confidence threshold - 80% was too restrictive
# Analysis: With wider Fib zones and better R:R, lower confidence is acceptable
# The tight 80% threshold combined with tight Fib zones left almost no signals
MIN_CONFIDENCE_THRESHOLD = 0.48         # v2.8.1: REDUCED from 0.50 - rejection analysis: 48-50% confidence had 100% win rate (+600 pips)
HIGH_CONFIDENCE_THRESHOLD = 0.75         # v1.7.0: REDUCED from 0.90 - achievable premium tier

# ============================================================================
# v2.9.0: DATA-DRIVEN FILTERS (from 85-trade analysis Dec 2025)
# ============================================================================
# Analysis findings:
#   - Volume >= 0.50: 70% win rate vs 43% without
#   - Confidence > 0.75: 42% win rate (paradox - higher = worse)
#
# Volume ratio filter - reject low volume signals
MIN_VOLUME_RATIO = 0.50                  # Global minimum (75% WR when >= 0.50)
VOLUME_FILTER_ENABLED = True             # Enable/disable volume filter
ALLOW_NO_VOLUME_DATA = True              # Allow signals when volume data unavailable

# Confidence cap - reject overconfident signals (paradox: higher conf = worse)
MAX_CONFIDENCE_THRESHOLD = 0.75          # Cap at 75% (42% WR above this)

# ============================================================================
# v2.10.0: MACD MOMENTUM ALIGNMENT FILTER (from 56-trade analysis Dec 2025)
# ============================================================================
# Analysis findings (60-day trade_log + alert_history correlation):
#   - MACD aligned with trade direction: 60% win rate, -$12/trade avg
#   - MACD against trade direction: 38% win rate, -$70/trade avg
#   - BULL trades + bullish MACD momentum: 71.4% win rate, +$69 total (BEST)
#   - BEAR trades + bearish MACD momentum: 42.9% win rate, -$492 total
#   - Misaligned trades: 37-39% win rate, -$1,472 total
#
# Filter logic: Check if MACD momentum supports the trade direction
#   - BULL signals: require bullish MACD momentum (line > signal)
#   - BEAR signals: require bearish MACD momentum (line < signal)
#
# NOTE: This does NOT require a fresh MACD crossover at entry time.
#       It simply checks the current momentum state - if MACD has been
#       bullish for 10 candles, BULL trades pass, BEAR trades get blocked.
#
MACD_ALIGNMENT_FILTER_ENABLED = True     # Enable MACD momentum filter
MACD_ALIGNMENT_MODE = 'momentum'         # 'momentum' = line vs signal direction
                                         # 'histogram' = histogram sign only
MACD_MIN_STRENGTH = 0.0                  # Minimum |macd_line - macd_signal| to count as aligned
                                         # 0.0 = any alignment counts (recommended start)
                                         # Higher values = require stronger momentum separation

# Pair-specific MACD filter overrides
# Set to False to disable MACD filter for specific pairs that behave differently
PAIR_MACD_FILTER_OVERRIDES = {
    # Pairs where MACD filter shows clear benefit (use default True)
    # 'CS.D.USDJPY.MINI.IP': True,  # 40% aligned vs 20% against - big improvement
    # 'CS.D.AUDJPY.MINI.IP': True,  # 83% aligned vs 50% against
    # 'CS.D.EURJPY.MINI.IP': True,  # 83% aligned vs 50% against

    # Pairs where MACD alignment is less predictive (might disable)
    # 'CS.D.NZDUSD.MINI.IP': False,  # Small sample, unclear pattern
}

def is_macd_filter_enabled(epic: str) -> bool:
    """Check if MACD filter is enabled for a specific pair."""
    if not MACD_ALIGNMENT_FILTER_ENABLED:
        return False
    override = PAIR_MACD_FILTER_OVERRIDES.get(epic)
    if override is not None:
        return override
    return True

def check_macd_alignment(signal_type: str, macd_line: float, macd_signal: float,
                         macd_histogram: float = None) -> tuple[bool, str]:
    """
    Check if MACD momentum aligns with trade direction.

    This checks the CURRENT state of MACD, not whether a crossover just happened.
    If MACD has been bullish for many candles, BULL trades pass, BEAR trades fail.

    Args:
        signal_type: 'BULL' or 'BEAR'
        macd_line: MACD line value
        macd_signal: MACD signal line value
        macd_histogram: MACD histogram value (optional, for 'histogram' mode)

    Returns:
        Tuple of (is_aligned: bool, reason: str)
    """
    if MACD_ALIGNMENT_MODE == 'histogram':
        # Histogram mode: check histogram sign matches direction
        if macd_histogram is None:
            return True, "No histogram data"
        if signal_type == 'BULL':
            aligned = macd_histogram > 0
            direction = 'bullish' if macd_histogram > 0 else 'bearish'
        else:
            aligned = macd_histogram < 0
            direction = 'bearish' if macd_histogram < 0 else 'bullish'
        reason = f"MACD histogram {direction} ({macd_histogram:.6f})"
    else:
        # Momentum mode (default): check MACD line vs signal line
        if macd_line is None or macd_signal is None:
            return True, "No MACD data"

        macd_diff = macd_line - macd_signal
        min_strength = MACD_MIN_STRENGTH

        if signal_type == 'BULL':
            # BULL trade needs bullish momentum (line > signal)
            aligned = macd_diff > min_strength
            direction = "bullish" if macd_diff > 0 else "bearish"
        else:
            # BEAR trade needs bearish momentum (line < signal)
            aligned = macd_diff < -min_strength
            direction = "bearish" if macd_diff < 0 else "bullish"

        reason = f"MACD momentum {direction} (diff={macd_diff:.6f})"

    return aligned, reason

# Scoring weights (must sum to 1.0)
# v2.2.0: Balanced 5-component scoring (each 20%)
# - EMA alignment: ATR-normalized (3 ATR from EMA = max)
# - Swing break quality: Body %, break strength, recency (NOW IMPLEMENTED)
# - Volume strength: Gradient scoring based on spike magnitude (was binary)
# - Pullback quality: Combined zone + Fib accuracy (was over-weighted at 40%)
# - R:R ratio: Scales toward 3:1
CONFIDENCE_WEIGHTS = {
    'ema_alignment': 0.20,               # v2.2.0: ATR-normalized EMA distance
    'swing_break_quality': 0.20,         # v2.2.0: NOW IMPLEMENTED - body %, strength, recency
    'volume_strength': 0.20,             # v2.2.0: Gradient scoring (was binary 15%/5%)
    'pullback_quality': 0.20,            # v2.2.0: Combined zone + Fib (was 40% split)
    'rr_ratio': 0.20,                    # v2.2.0: R:R quality toward 3:1
}

# ============================================================================
# LOGGING & DEBUG
# ============================================================================

ENABLE_DEBUG_LOGGING = True              # Detailed logging for development
LOG_REJECTED_SIGNALS = True              # Log why signals were rejected
LOG_SWING_DETECTION = False              # Log swing point detection (verbose)
LOG_EMA_CHECKS = False                   # Log EMA alignment checks (verbose)

# ============================================================================
# REJECTION TRACKING (for strategy improvement analysis)
# ============================================================================
# Store rejection data to database for later analysis in Streamlit dashboard
# Captures market state at each rejection point to identify improvement areas
# Storage: ~1-2 MB/day (~500-900 rejections/day across 9 pairs)

REJECTION_TRACKING_ENABLED = True        # Toggle to enable/disable DB storage
REJECTION_BATCH_SIZE = 50                # Batch inserts for performance
REJECTION_LOG_TO_CONSOLE = False         # Also log rejections to console (verbose)
REJECTION_RETENTION_DAYS = 90            # Auto-cleanup data older than this

# ============================================================================
# BACKTEST SETTINGS
# ============================================================================

BACKTEST_SPREAD_PIPS = 1.5               # Assumed spread for backtesting
BACKTEST_SLIPPAGE_PIPS = 0.5             # Assumed slippage for backtesting

# ============================================================================
# SCALP REVERSAL OVERRIDE (counter-trend)
# ============================================================================
SCALP_REVERSAL_ENABLED = True
SCALP_REVERSAL_MIN_RUNWAY_PIPS = 15.0
SCALP_REVERSAL_MIN_ENTRY_MOMENTUM = 0.60
SCALP_REVERSAL_BLOCK_REGIMES = ['breakout']
SCALP_REVERSAL_BLOCK_VOLATILITY_STATES = ['high']
SCALP_REVERSAL_ALLOW_RSI_EXTREMES = True

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_pip_value(epic: str) -> float:
    """Get pip value for a given epic."""
    return PAIR_PIP_VALUES.get(epic, 0.0001)

def is_session_allowed(hour_utc: int) -> bool:
    """Check if current hour is in allowed trading session."""
    if not SESSION_FILTER_ENABLED:
        return True

    # London: 07:00-16:00 UTC
    # NY: 12:00-21:00 UTC
    # Overlap: 12:00-16:00 UTC

    if BLOCK_ASIAN_SESSION and (hour_utc >= 21 or hour_utc < 7):
        return False

    return 7 <= hour_utc <= 21  # London open to NY close

def get_optimal_pullback_zone() -> tuple:
    """Get optimal Fibonacci pullback zone."""
    return FIB_OPTIMAL_ZONE
