-- Migration: Add config_set column for dual live/demo trading
-- Purpose: Allow multiple active configs (one per environment) so live and demo
--          scanners can run different strategy parameters simultaneously.
-- Date: 2026-04-11

BEGIN;

-- Step 1: Add config_set column to global config
ALTER TABLE smc_simple_global_config
  ADD COLUMN IF NOT EXISTS config_set VARCHAR(20) NOT NULL DEFAULT 'live';

-- Step 2: Tag existing active row as 'live'
UPDATE smc_simple_global_config SET config_set = 'live' WHERE is_active = TRUE;
UPDATE smc_simple_global_config SET config_set = 'live' WHERE is_active = FALSE AND config_set = 'live';

-- Step 3: Unique constraint - only one active config per config_set
-- Drop if exists first (idempotent)
DROP INDEX IF EXISTS idx_active_config_per_set;
CREATE UNIQUE INDEX idx_active_config_per_set
  ON smc_simple_global_config(config_set) WHERE is_active = TRUE;

-- Step 4: Clone the active live config as demo config
-- Uses a dynamic approach to copy all columns except id (auto-generated)
INSERT INTO smc_simple_global_config (
  version, is_active, strategy_name, strategy_status,
  htf_timeframe, ema_period, ema_buffer_pips, require_close_beyond_ema,
  min_distance_from_ema_pips, trigger_timeframe, swing_lookback_bars,
  swing_strength_bars, require_body_close_break, wick_tolerance_pips,
  volume_confirmation_enabled, volume_sma_period, volume_spike_multiplier,
  use_dynamic_swing_lookback, swing_lookback_atr_low, swing_lookback_atr_high,
  swing_lookback_min, swing_lookback_max, entry_timeframe, pullback_enabled,
  fib_pullback_min, fib_pullback_max, fib_optimal_zone_min, fib_optimal_zone_max,
  max_pullback_wait_bars, pullback_confirmation_bars, momentum_mode_enabled,
  momentum_min_depth, momentum_max_depth, momentum_confidence_penalty,
  use_atr_swing_validation, atr_period, min_swing_atr_multiplier,
  fallback_min_swing_pips, momentum_quality_enabled, min_breakout_atr_ratio,
  min_body_percentage, limit_order_enabled, limit_expiry_minutes,
  pullback_offset_atr_factor, pullback_offset_min_pips, pullback_offset_max_pips,
  momentum_offset_pips, min_risk_after_offset_pips, max_sl_atr_multiplier,
  max_sl_absolute_pips, max_risk_after_offset_pips, min_rr_ratio,
  optimal_rr_ratio, max_rr_ratio, sl_buffer_pips, sl_atr_multiplier,
  use_atr_stop, min_tp_pips, use_swing_target, tp_structure_lookback,
  risk_per_trade_pct, session_filter_enabled, london_session_start,
  london_session_end, ny_session_start, ny_session_end, allowed_sessions,
  block_asian_session, max_concurrent_signals, signal_cooldown_hours,
  adaptive_cooldown_config, min_confidence_threshold, max_confidence_threshold,
  high_confidence_threshold, confidence_weights, min_volume_ratio,
  volume_filter_enabled, allow_no_volume_data, volume_adjusted_confidence_enabled,
  high_volume_threshold, atr_adjusted_confidence_enabled, low_atr_threshold,
  high_atr_threshold, ema_distance_adjusted_confidence_enabled,
  near_ema_threshold_pips, far_ema_threshold_pips,
  macd_alignment_filter_enabled, macd_alignment_mode, macd_min_strength,
  enable_debug_logging, log_rejected_signals, log_swing_detection,
  log_ema_checks, rejection_tracking_enabled, rejection_batch_size,
  rejection_log_to_console, rejection_retention_days,
  backtest_spread_pips, backtest_slippage_pips, enabled_pairs, pair_pip_values,
  updated_by, change_reason,
  fixed_sl_tp_override_enabled, fixed_stop_loss_pips, fixed_take_profit_pips,
  swing_proximity_enabled, swing_proximity_min_distance_pips,
  swing_proximity_strict_mode, swing_proximity_resistance_buffer,
  swing_proximity_support_buffer, swing_proximity_lookback_swings,
  ema_slope_validation_enabled, ema_slope_lookback_bars,
  ema_slope_min_atr_multiplier, market_order_min_confidence,
  market_order_min_ema_slope, low_confidence_extra_offset,
  max_extension_atr, max_extension_atr_enabled,
  momentum_staleness_enabled, max_momentum_staleness_bars,
  scalp_mode_enabled, scalp_tp_pips, scalp_sl_pips, scalp_max_spread_pips,
  scalp_htf_timeframe, scalp_trigger_timeframe, scalp_entry_timeframe,
  scalp_ema_period, scalp_min_confidence, scalp_disable_ema_slope_validation,
  scalp_disable_swing_proximity, scalp_disable_volume_filter,
  scalp_disable_macd_filter, scalp_use_momentum_only, scalp_momentum_min_depth,
  scalp_fib_pullback_min, scalp_fib_pullback_max, scalp_cooldown_minutes,
  scalp_require_tight_spread, scalp_swing_lookback_bars,
  scalp_range_position_threshold, scalp_enable_claude_ai,
  scalp_use_market_orders, scalp_qualification_enabled,
  scalp_qualification_mode, scalp_min_qualification_score,
  scalp_rsi_filter_enabled, scalp_two_pole_filter_enabled,
  scalp_macd_filter_enabled, scalp_rsi_bull_min, scalp_rsi_bull_max,
  scalp_rsi_bear_min, scalp_rsi_bear_max, scalp_two_pole_bull_threshold,
  scalp_two_pole_bear_threshold, scalp_micro_regime_enabled,
  scalp_consecutive_candles_enabled, scalp_anti_chop_enabled,
  scalp_body_dominance_enabled, scalp_micro_range_enabled,
  scalp_momentum_candle_enabled, scalp_consecutive_candles_min,
  scalp_anti_chop_lookback, scalp_anti_chop_max_alternations,
  scalp_body_dominance_lookback, scalp_body_dominance_ratio,
  scalp_micro_range_lookback, scalp_micro_range_min_pips,
  scalp_momentum_candle_multiplier, scalp_micro_pullback_lookback,
  scalp_require_htf_alignment, scalp_momentum_only_filter,
  scalp_entry_rsi_buy_max, scalp_entry_rsi_sell_min,
  scalp_min_ema_distance_pips,
  pattern_confirmation_enabled, pattern_confirmation_mode,
  pattern_min_strength, pattern_pin_bar_enabled, pattern_engulfing_enabled,
  pattern_inside_bar_enabled, pattern_hammer_shooter_enabled,
  pattern_confidence_boost, rsi_divergence_enabled, rsi_divergence_mode,
  rsi_divergence_lookback, rsi_divergence_min_strength,
  rsi_divergence_confidence_boost, macd_alignment_enabled,
  macd_alignment_required, macd_alignment_confidence_boost,
  pattern_as_entry_enabled, pattern_entry_min_strength,
  divergence_as_entry_enabled, divergence_entry_min_strength,
  scalp_use_limit_orders, scalp_require_rejection_candle,
  scalp_rejection_min_strength, scalp_use_market_on_rejection,
  scalp_require_entry_candle_alignment, scalp_use_market_on_entry_alignment,
  scalp_reversal_enabled, scalp_reversal_min_runway_pips,
  scalp_reversal_min_entry_momentum, scalp_reversal_block_regimes,
  scalp_reversal_block_volatility_states, scalp_reversal_allow_rsi_extremes,
  htf_bias_enabled, htf_bias_min_threshold,
  htf_bias_confidence_multiplier_enabled,
  scalp_block_global_high_volatility,
  regime_sl_tp_enabled, trending_sl_mult, trending_tp_mult,
  ranging_sl_mult, ranging_tp_mult, high_vol_sl_mult, high_vol_tp_mult,
  low_vol_sl_mult, low_vol_tp_mult, block_htf_start_position,
  rsi_direction_filter_enabled, rsi_sell_min, rsi_buy_max,
  min_adx_threshold, blocked_hours_utc,
  breakout_sl_mult, breakout_tp_mult,
  atr_normalized_sl_tp_enabled, atr_reference_pips,
  atr_scale_min, atr_scale_max,
  rolling_perf_enabled, rolling_perf_window,
  rolling_perf_low_wr_threshold, rolling_perf_very_low_wr_threshold,
  rolling_perf_high_wr_threshold, rolling_perf_low_wr_penalty,
  rolling_perf_very_low_wr_penalty, rolling_perf_high_wr_bonus,
  sweep_protection_enabled, sweep_protection_mode,
  sweep_rsi_threshold_buy, sweep_rsi_threshold_sell,
  sweep_max_ema_distance_pips, sweep_max_ema_distance_pips_jpy,
  sweep_min_conditions,
  config_set
)
SELECT
  version, TRUE, strategy_name, strategy_status,
  htf_timeframe, ema_period, ema_buffer_pips, require_close_beyond_ema,
  min_distance_from_ema_pips, trigger_timeframe, swing_lookback_bars,
  swing_strength_bars, require_body_close_break, wick_tolerance_pips,
  volume_confirmation_enabled, volume_sma_period, volume_spike_multiplier,
  use_dynamic_swing_lookback, swing_lookback_atr_low, swing_lookback_atr_high,
  swing_lookback_min, swing_lookback_max, entry_timeframe, pullback_enabled,
  fib_pullback_min, fib_pullback_max, fib_optimal_zone_min, fib_optimal_zone_max,
  max_pullback_wait_bars, pullback_confirmation_bars, momentum_mode_enabled,
  momentum_min_depth, momentum_max_depth, momentum_confidence_penalty,
  use_atr_swing_validation, atr_period, min_swing_atr_multiplier,
  fallback_min_swing_pips, momentum_quality_enabled, min_breakout_atr_ratio,
  min_body_percentage, limit_order_enabled, limit_expiry_minutes,
  pullback_offset_atr_factor, pullback_offset_min_pips, pullback_offset_max_pips,
  momentum_offset_pips, min_risk_after_offset_pips, max_sl_atr_multiplier,
  max_sl_absolute_pips, max_risk_after_offset_pips, min_rr_ratio,
  optimal_rr_ratio, max_rr_ratio, sl_buffer_pips, sl_atr_multiplier,
  use_atr_stop, min_tp_pips, use_swing_target, tp_structure_lookback,
  risk_per_trade_pct, session_filter_enabled, london_session_start,
  london_session_end, ny_session_start, ny_session_end, allowed_sessions,
  block_asian_session, max_concurrent_signals, signal_cooldown_hours,
  adaptive_cooldown_config, min_confidence_threshold, max_confidence_threshold,
  high_confidence_threshold, confidence_weights, min_volume_ratio,
  volume_filter_enabled, allow_no_volume_data, volume_adjusted_confidence_enabled,
  high_volume_threshold, atr_adjusted_confidence_enabled, low_atr_threshold,
  high_atr_threshold, ema_distance_adjusted_confidence_enabled,
  near_ema_threshold_pips, far_ema_threshold_pips,
  macd_alignment_filter_enabled, macd_alignment_mode, macd_min_strength,
  enable_debug_logging, log_rejected_signals, log_swing_detection,
  log_ema_checks, rejection_tracking_enabled, rejection_batch_size,
  rejection_log_to_console, rejection_retention_days,
  backtest_spread_pips, backtest_slippage_pips, enabled_pairs, pair_pip_values,
  'migration', 'Cloned from live config for dual live/demo trading',
  fixed_sl_tp_override_enabled, fixed_stop_loss_pips, fixed_take_profit_pips,
  swing_proximity_enabled, swing_proximity_min_distance_pips,
  swing_proximity_strict_mode, swing_proximity_resistance_buffer,
  swing_proximity_support_buffer, swing_proximity_lookback_swings,
  ema_slope_validation_enabled, ema_slope_lookback_bars,
  ema_slope_min_atr_multiplier, market_order_min_confidence,
  market_order_min_ema_slope, low_confidence_extra_offset,
  max_extension_atr, max_extension_atr_enabled,
  momentum_staleness_enabled, max_momentum_staleness_bars,
  scalp_mode_enabled, scalp_tp_pips, scalp_sl_pips, scalp_max_spread_pips,
  scalp_htf_timeframe, scalp_trigger_timeframe, scalp_entry_timeframe,
  scalp_ema_period, scalp_min_confidence, scalp_disable_ema_slope_validation,
  scalp_disable_swing_proximity, scalp_disable_volume_filter,
  scalp_disable_macd_filter, scalp_use_momentum_only, scalp_momentum_min_depth,
  scalp_fib_pullback_min, scalp_fib_pullback_max, scalp_cooldown_minutes,
  scalp_require_tight_spread, scalp_swing_lookback_bars,
  scalp_range_position_threshold, scalp_enable_claude_ai,
  scalp_use_market_orders, scalp_qualification_enabled,
  scalp_qualification_mode, scalp_min_qualification_score,
  scalp_rsi_filter_enabled, scalp_two_pole_filter_enabled,
  scalp_macd_filter_enabled, scalp_rsi_bull_min, scalp_rsi_bull_max,
  scalp_rsi_bear_min, scalp_rsi_bear_max, scalp_two_pole_bull_threshold,
  scalp_two_pole_bear_threshold, scalp_micro_regime_enabled,
  scalp_consecutive_candles_enabled, scalp_anti_chop_enabled,
  scalp_body_dominance_enabled, scalp_micro_range_enabled,
  scalp_momentum_candle_enabled, scalp_consecutive_candles_min,
  scalp_anti_chop_lookback, scalp_anti_chop_max_alternations,
  scalp_body_dominance_lookback, scalp_body_dominance_ratio,
  scalp_micro_range_lookback, scalp_micro_range_min_pips,
  scalp_momentum_candle_multiplier, scalp_micro_pullback_lookback,
  scalp_require_htf_alignment, scalp_momentum_only_filter,
  scalp_entry_rsi_buy_max, scalp_entry_rsi_sell_min,
  scalp_min_ema_distance_pips,
  pattern_confirmation_enabled, pattern_confirmation_mode,
  pattern_min_strength, pattern_pin_bar_enabled, pattern_engulfing_enabled,
  pattern_inside_bar_enabled, pattern_hammer_shooter_enabled,
  pattern_confidence_boost, rsi_divergence_enabled, rsi_divergence_mode,
  rsi_divergence_lookback, rsi_divergence_min_strength,
  rsi_divergence_confidence_boost, macd_alignment_enabled,
  macd_alignment_required, macd_alignment_confidence_boost,
  pattern_as_entry_enabled, pattern_entry_min_strength,
  divergence_as_entry_enabled, divergence_entry_min_strength,
  scalp_use_limit_orders, scalp_require_rejection_candle,
  scalp_rejection_min_strength, scalp_use_market_on_rejection,
  scalp_require_entry_candle_alignment, scalp_use_market_on_entry_alignment,
  scalp_reversal_enabled, scalp_reversal_min_runway_pips,
  scalp_reversal_min_entry_momentum, scalp_reversal_block_regimes,
  scalp_reversal_block_volatility_states, scalp_reversal_allow_rsi_extremes,
  htf_bias_enabled, htf_bias_min_threshold,
  htf_bias_confidence_multiplier_enabled,
  scalp_block_global_high_volatility,
  regime_sl_tp_enabled, trending_sl_mult, trending_tp_mult,
  ranging_sl_mult, ranging_tp_mult, high_vol_sl_mult, high_vol_tp_mult,
  low_vol_sl_mult, low_vol_tp_mult, block_htf_start_position,
  rsi_direction_filter_enabled, rsi_sell_min, rsi_buy_max,
  min_adx_threshold, blocked_hours_utc,
  breakout_sl_mult, breakout_tp_mult,
  atr_normalized_sl_tp_enabled, atr_reference_pips,
  atr_scale_min, atr_scale_max,
  rolling_perf_enabled, rolling_perf_window,
  rolling_perf_low_wr_threshold, rolling_perf_very_low_wr_threshold,
  rolling_perf_high_wr_threshold, rolling_perf_low_wr_penalty,
  rolling_perf_very_low_wr_penalty, rolling_perf_high_wr_bonus,
  sweep_protection_enabled, sweep_protection_mode,
  sweep_rsi_threshold_buy, sweep_rsi_threshold_sell,
  sweep_max_ema_distance_pips, sweep_max_ema_distance_pips_jpy,
  sweep_min_conditions,
  'demo'  -- config_set = demo
FROM smc_simple_global_config
WHERE is_active = TRUE AND config_set = 'live';

-- Step 5: Clone pair overrides for the new demo config
-- Get the new demo config id and clone all pair overrides
DO $$
DECLARE
  live_config_id INTEGER;
  demo_config_id INTEGER;
BEGIN
  SELECT id INTO live_config_id FROM smc_simple_global_config WHERE is_active = TRUE AND config_set = 'live';
  SELECT id INTO demo_config_id FROM smc_simple_global_config WHERE is_active = TRUE AND config_set = 'demo';

  IF demo_config_id IS NOT NULL AND live_config_id IS NOT NULL THEN
    INSERT INTO smc_simple_pair_overrides (
      config_id, epic, is_enabled, description, parameter_overrides,
      high_volume_confidence, low_atr_confidence, high_atr_confidence,
      near_ema_confidence, far_ema_confidence, allow_asian_session,
      sl_buffer_pips, min_confidence, macd_filter_enabled, min_volume_ratio,
      blocking_conditions, updated_by, change_reason,
      max_confidence, fixed_stop_loss_pips, fixed_take_profit_pips,
      fib_pullback_min_bull, fib_pullback_min_bear,
      fib_pullback_max_bull, fib_pullback_max_bear,
      momentum_min_depth_bull, momentum_min_depth_bear,
      min_volume_ratio_bull, min_volume_ratio_bear,
      min_confidence_bull, min_confidence_bear,
      direction_overrides_enabled, min_swing_atr_multiplier,
      swing_lookback_bars, smc_conflict_tolerance,
      swing_proximity_enabled, swing_proximity_min_distance_pips,
      swing_proximity_strict_mode, ema_period, ema_slope_validation_enabled,
      stop_offset_pips, max_extension_atr, max_momentum_staleness_bars,
      scalp_enabled, scalp_tp_pips, scalp_sl_pips, scalp_max_spread_pips,
      scalp_ema_period, scalp_swing_lookback_bars, scalp_limit_offset_pips,
      scalp_htf_timeframe, scalp_trigger_timeframe, scalp_entry_timeframe,
      scalp_min_confidence, scalp_cooldown_minutes,
      scalp_swing_break_tolerance_pips, scalp_qualification_mode,
      scalp_fib_pullback_min, scalp_reversal_enabled,
      scalp_reversal_min_runway_pips, htf_bias_mode, htf_bias_min_threshold,
      scalp_sr_tolerance_pips, scalp_require_ema_stack_alignment,
      scalp_block_ranging_market, scalp_block_low_volatility_trending,
      scalp_min_adx, scalp_rsi_block_buy_min, scalp_rsi_block_buy_max,
      scalp_rsi_block_sell_min, scalp_rsi_block_sell_max,
      scalp_blocked_hours_utc, scalp_block_global_high_volatility
    )
    SELECT
      demo_config_id, epic, is_enabled, description, parameter_overrides,
      high_volume_confidence, low_atr_confidence, high_atr_confidence,
      near_ema_confidence, far_ema_confidence, allow_asian_session,
      sl_buffer_pips, min_confidence, macd_filter_enabled, min_volume_ratio,
      blocking_conditions, 'migration', 'Cloned from live for dual trading',
      max_confidence, fixed_stop_loss_pips, fixed_take_profit_pips,
      fib_pullback_min_bull, fib_pullback_min_bear,
      fib_pullback_max_bull, fib_pullback_max_bear,
      momentum_min_depth_bull, momentum_min_depth_bear,
      min_volume_ratio_bull, min_volume_ratio_bear,
      min_confidence_bull, min_confidence_bear,
      direction_overrides_enabled, min_swing_atr_multiplier,
      swing_lookback_bars, smc_conflict_tolerance,
      swing_proximity_enabled, swing_proximity_min_distance_pips,
      swing_proximity_strict_mode, ema_period, ema_slope_validation_enabled,
      stop_offset_pips, max_extension_atr, max_momentum_staleness_bars,
      scalp_enabled, scalp_tp_pips, scalp_sl_pips, scalp_max_spread_pips,
      scalp_ema_period, scalp_swing_lookback_bars, scalp_limit_offset_pips,
      scalp_htf_timeframe, scalp_trigger_timeframe, scalp_entry_timeframe,
      scalp_min_confidence, scalp_cooldown_minutes,
      scalp_swing_break_tolerance_pips, scalp_qualification_mode,
      scalp_fib_pullback_min, scalp_reversal_enabled,
      scalp_reversal_min_runway_pips, htf_bias_mode, htf_bias_min_threshold,
      scalp_sr_tolerance_pips, scalp_require_ema_stack_alignment,
      scalp_block_ranging_market, scalp_block_low_volatility_trending,
      scalp_min_adx, scalp_rsi_block_buy_min, scalp_rsi_block_buy_max,
      scalp_rsi_block_sell_min, scalp_rsi_block_sell_max,
      scalp_blocked_hours_utc, scalp_block_global_high_volatility
    FROM smc_simple_pair_overrides
    WHERE config_id = live_config_id;

    RAISE NOTICE 'Cloned % pair overrides from live (id=%) to demo (id=%)',
      (SELECT count(*) FROM smc_simple_pair_overrides WHERE config_id = demo_config_id),
      live_config_id, demo_config_id;
  ELSE
    RAISE NOTICE 'Could not find live or demo config - skipping pair override clone';
  END IF;
END $$;

COMMIT;
